import type { Category } from "@/types"

export const categories: Category[] = [
  {
    id: "cat_01",
    name: "Sherwanis",
    slug: "sherwanis",
    description: "Ceremonial sherwanis in velvet, jamawar and hand-embroidered silk.",
    image: "maroon",
    parent: null,
    productCount: 48,
    collections: ["Wedding Collection", "Eid Collection"],
    visibility: "visible",
    status: "active",
    featured: true,
    displayOrder: 1,
    metaTitle: "Sherwanis | T-Mark Apparel",
    metaDescription: "Explore T-Mark's signature sherwanis for weddings and occasions.",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-07-02T09:00:00Z",
    activity: [
      { id: "a1", label: "12 products added", timestamp: "2026-07-02T09:00:00Z" },
      { id: "a2", label: "Featured on homepage", timestamp: "2026-06-20T09:00:00Z" },
    ],
  },
  {
    id: "cat_02",
    name: "Groom Sets",
    slug: "groom-sets",
    description: "Complete groom ensembles paired with accessories and footwear.",
    image: "emerald",
    parent: "Sherwanis",
    productCount: 16,
    collections: ["Wedding Collection", "Premium Collection"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 2,
    metaTitle: "Groom Sets | T-Mark Apparel",
    metaDescription: "Curated groom sets with coordinated tailoring and accessories.",
    createdAt: "2026-03-05T09:00:00Z",
    updatedAt: "2026-06-28T09:00:00Z",
    activity: [
      { id: "a1", label: "Description updated", timestamp: "2026-06-28T09:00:00Z" },
    ],
  },
  {
    id: "cat_03",
    name: "Prince Coats",
    slug: "prince-coats",
    description: "Structured prince coats with satin lapels and mandarin collars.",
    image: "ivory",
    parent: null,
    productCount: 34,
    collections: ["Wedding Collection", "New Arrivals"],
    visibility: "visible",
    status: "active",
    featured: true,
    displayOrder: 3,
    metaTitle: "Prince Coats | T-Mark Apparel",
    metaDescription: "Timeless prince coats tailored for grooms and guests.",
    createdAt: "2026-02-18T09:00:00Z",
    updatedAt: "2026-06-30T09:00:00Z",
    activity: [
      { id: "a1", label: "6 products restocked", timestamp: "2026-06-30T09:00:00Z" },
    ],
  },
  {
    id: "cat_04",
    name: "Bandhgala",
    slug: "bandhgala",
    description: "Bandhgala jackets with brooch detailing for formal events.",
    image: "navy",
    parent: "Prince Coats",
    productCount: 12,
    collections: ["Premium Collection"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 4,
    metaTitle: "Bandhgala | T-Mark Apparel",
    metaDescription: "Refined bandhgala jackets for a sharp formal silhouette.",
    createdAt: "2026-04-12T09:00:00Z",
    updatedAt: "2026-06-15T09:00:00Z",
    activity: [
      { id: "a1", label: "Category created", timestamp: "2026-04-12T09:00:00Z" },
    ],
  },
  {
    id: "cat_05",
    name: "Waistcoats",
    slug: "waistcoats",
    description: "Five-button and peak-lapel waistcoats in wool and cotton.",
    image: "charcoal",
    parent: null,
    productCount: 41,
    collections: ["Best Sellers", "New Arrivals"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 5,
    metaTitle: "Waistcoats | T-Mark Apparel",
    metaDescription: "Layer-ready waistcoats in a range of premium fabrics.",
    createdAt: "2026-01-22T09:00:00Z",
    updatedAt: "2026-06-25T09:00:00Z",
    activity: [
      { id: "a1", label: "Sort order changed", timestamp: "2026-06-25T09:00:00Z" },
    ],
  },
  {
    id: "cat_06",
    name: "Western Suiting",
    slug: "western-suiting",
    description: "Two and three-piece suits with half-canvas construction.",
    image: "black",
    parent: null,
    productCount: 57,
    collections: ["Best Sellers", "Premium Collection"],
    visibility: "visible",
    status: "active",
    featured: true,
    displayOrder: 6,
    metaTitle: "Western Suiting | T-Mark Apparel",
    metaDescription: "Modern western suiting tailored for business and black-tie.",
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
    activity: [
      { id: "a1", label: "8 products added", timestamp: "2026-07-01T09:00:00Z" },
    ],
  },
  {
    id: "cat_07",
    name: "Tuxedos",
    slug: "tuxedos",
    description: "Satin-lapel tuxedos with matching bow ties and cummerbunds.",
    image: "black",
    parent: "Western Suiting",
    productCount: 18,
    collections: ["Premium Collection", "New Arrivals"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 7,
    metaTitle: "Tuxedos | T-Mark Apparel",
    metaDescription: "Black-tie tuxedos finished with hand-set details.",
    createdAt: "2026-05-02T09:00:00Z",
    updatedAt: "2026-06-18T09:00:00Z",
    activity: [
      { id: "a1", label: "Visibility set to visible", timestamp: "2026-06-18T09:00:00Z" },
    ],
  },
  {
    id: "cat_08",
    name: "Shalwar Kameez",
    slug: "shalwar-kameez",
    description: "Embroidered and classic shalwar kameez in cotton and silk.",
    image: "sand",
    parent: null,
    productCount: 39,
    collections: ["Eid Collection", "Best Sellers"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 8,
    metaTitle: "Shalwar Kameez | T-Mark Apparel",
    metaDescription: "Everyday and occasion shalwar kameez, expertly finished.",
    createdAt: "2026-02-28T09:00:00Z",
    updatedAt: "2026-06-22T09:00:00Z",
    activity: [
      { id: "a1", label: "3 products archived", timestamp: "2026-06-22T09:00:00Z" },
    ],
  },
  {
    id: "cat_09",
    name: "Kurtas",
    slug: "kurtas",
    description: "Linen and raw-silk kurtas with mother-of-pearl buttons.",
    image: "sand",
    parent: null,
    productCount: 27,
    collections: ["Eid Collection", "New Arrivals"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 9,
    metaTitle: "Kurtas | T-Mark Apparel",
    metaDescription: "Breathable kurtas for festive and everyday wear.",
    createdAt: "2026-03-19T09:00:00Z",
    updatedAt: "2026-06-10T09:00:00Z",
    activity: [
      { id: "a1", label: "Banner image updated", timestamp: "2026-06-10T09:00:00Z" },
    ],
  },
  {
    id: "cat_10",
    name: "Accessories",
    slug: "accessories",
    description: "Brooches, pocket squares, stoles and formal footwear.",
    image: "ivory",
    parent: null,
    productCount: 0,
    collections: ["New Arrivals"],
    visibility: "hidden",
    status: "draft",
    featured: false,
    displayOrder: 10,
    metaTitle: "Accessories | T-Mark Apparel",
    metaDescription: "Finishing touches for the complete T-Mark look.",
    createdAt: "2026-06-08T09:00:00Z",
    updatedAt: "2026-06-08T09:00:00Z",
    activity: [
      { id: "a1", label: "Category created as draft", timestamp: "2026-06-08T09:00:00Z" },
    ],
  },
  {
    id: "cat_11",
    name: "Seasonal Sale",
    slug: "seasonal-sale",
    description: "Rotating markdowns across last-season tailoring.",
    image: "charcoal",
    parent: null,
    productCount: 22,
    collections: ["Best Sellers"],
    visibility: "hidden",
    status: "draft",
    featured: false,
    displayOrder: 11,
    metaTitle: "Seasonal Sale | T-Mark Apparel",
    metaDescription: "Limited-time pricing on selected T-Mark pieces.",
    createdAt: "2026-05-26T09:00:00Z",
    updatedAt: "2026-06-05T09:00:00Z",
    activity: [
      { id: "a1", label: "Hidden from storefront", timestamp: "2026-06-05T09:00:00Z" },
    ],
  },
  {
    id: "cat_12",
    name: "Summer Linen",
    slug: "summer-linen",
    description: "Lightweight linen tailoring for warm-weather occasions.",
    image: "sand",
    parent: null,
    productCount: 14,
    collections: ["New Arrivals"],
    visibility: "visible",
    status: "active",
    featured: false,
    displayOrder: 12,
    metaTitle: "Summer Linen | T-Mark Apparel",
    metaDescription: "Breathable linen suiting and separates for summer.",
    createdAt: "2026-06-30T09:00:00Z",
    updatedAt: "2026-07-03T09:00:00Z",
    activity: [
      { id: "a1", label: "Category created", timestamp: "2026-06-30T09:00:00Z" },
    ],
  },
]

export const PARENT_OPTIONS = categories
  .filter((c) => c.parent === null)
  .map((c) => c.name)
