import type { Collection } from "@/types"

export const collections: Collection[] = [
  {
    id: "col_01",
    name: "The Wedding Edit",
    subtitle: "Ceremonial tailoring for the modern groom",
    slug: "wedding-collection",
    description:
      "Our flagship bridal-season edit — sherwanis, prince coats and groom sets cut for the aisle and the after-party.",
    cover: "wedding",
    season: "Wedding",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "published",
    visibility: "visible",
    featured: true,
    productCount: 64,
    categories: ["Sherwanis", "Prince Coats", "Waistcoats"],
    scheduledFor: null,
    revenue: 8420000,
    views: 48200,
    conversion: 4.6,
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-07-03T09:00:00Z",
    activity: [
      { id: "a1", label: "6 products added", timestamp: "2026-07-03T09:00:00Z" },
      { id: "a2", label: "Hero banner updated", timestamp: "2026-06-24T09:00:00Z" },
    ],
  },
  {
    id: "col_02",
    name: "Luxury Velvet",
    subtitle: "Depth, sheen and hand-set embroidery",
    slug: "luxury-velvet",
    description:
      "A tightly curated capsule of velvet sherwanis and dinner jackets in maroon, emerald and midnight.",
    cover: "velvet",
    season: "Festive",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "published",
    visibility: "visible",
    featured: true,
    productCount: 22,
    categories: ["Sherwanis", "Western Suiting"],
    scheduledFor: null,
    revenue: 5130000,
    views: 26800,
    conversion: 5.2,
    createdAt: "2026-03-12T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
    activity: [
      { id: "a1", label: "Featured on homepage", timestamp: "2026-07-01T09:00:00Z" },
    ],
  },
  {
    id: "col_03",
    name: "Winter 2026",
    subtitle: "Heavier cloths, sharper silhouettes",
    slug: "winter-2026",
    description:
      "Flannel, tweed and wool-blend suiting built for the colder months. Scheduled to go live ahead of the season.",
    cover: "winter",
    season: "Winter 2026",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "scheduled",
    visibility: "hidden",
    featured: false,
    productCount: 38,
    categories: ["Western Suiting", "Waistcoats", "Prince Coats"],
    scheduledFor: "2026-09-01T09:00:00Z",
    revenue: 0,
    views: 0,
    conversion: 0,
    createdAt: "2026-06-18T09:00:00Z",
    updatedAt: "2026-07-02T09:00:00Z",
    activity: [
      { id: "a1", label: "Scheduled for Sep 1", timestamp: "2026-07-02T09:00:00Z" },
    ],
  },
  {
    id: "col_04",
    name: "Best Sellers",
    subtitle: "The pieces our clients keep coming back for",
    slug: "best-sellers",
    description:
      "An always-on edit of the highest-performing tailoring across every category, refreshed weekly.",
    cover: "bestsellers",
    season: "Evergreen",
    type: "smart",
    ruleMatch: "all",
    rules: [
      { id: "r1", field: "tag", operator: "is", value: "Best Seller" },
    ],
    status: "published",
    visibility: "visible",
    featured: true,
    productCount: 40,
    categories: ["Western Suiting", "Waistcoats", "Shalwar Kameez", "Kurtas"],
    scheduledFor: null,
    revenue: 6740000,
    views: 61400,
    conversion: 3.9,
    createdAt: "2026-01-20T09:00:00Z",
    updatedAt: "2026-07-04T09:00:00Z",
    activity: [
      { id: "a1", label: "Auto-refreshed", timestamp: "2026-07-04T09:00:00Z" },
    ],
  },
  {
    id: "col_05",
    name: "New Arrivals",
    subtitle: "Fresh off the atelier floor",
    slug: "new-arrivals",
    description:
      "The latest drops across ready-to-wear, updated as new pieces are published.",
    cover: "newarrivals",
    season: "Evergreen",
    type: "smart",
    ruleMatch: "all",
    rules: [
      { id: "r1", field: "days_since_added", operator: "less_than", value: "30" },
    ],
    status: "published",
    visibility: "visible",
    featured: false,
    productCount: 28,
    categories: ["Kurtas", "Waistcoats", "Western Suiting"],
    scheduledFor: null,
    revenue: 2180000,
    views: 33900,
    conversion: 3.1,
    createdAt: "2026-02-14T09:00:00Z",
    updatedAt: "2026-07-03T09:00:00Z",
    activity: [
      { id: "a1", label: "8 products added", timestamp: "2026-07-03T09:00:00Z" },
    ],
  },
  {
    id: "col_06",
    name: "Premium Collection",
    subtitle: "Made-to-measure, no compromises",
    slug: "premium-collection",
    description:
      "Our top tier — full-canvas construction, rare cloths and bespoke finishing for discerning clients.",
    cover: "premium",
    season: "Evergreen",
    type: "smart",
    ruleMatch: "all",
    rules: [
      { id: "r1", field: "price", operator: "greater_than", value: "150000" },
      { id: "r2", field: "fabric", operator: "is_not", value: "Egyptian Cotton" },
    ],
    status: "published",
    visibility: "visible",
    featured: true,
    productCount: 31,
    categories: ["Western Suiting", "Prince Coats", "Sherwanis"],
    scheduledFor: null,
    revenue: 9260000,
    views: 21500,
    conversion: 6.8,
    createdAt: "2026-01-08T09:00:00Z",
    updatedAt: "2026-06-29T09:00:00Z",
    activity: [
      { id: "a1", label: "Conversion up 0.4%", timestamp: "2026-06-29T09:00:00Z" },
    ],
  },
  {
    id: "col_07",
    name: "Festive Collection",
    subtitle: "Eid-ready occasion wear",
    slug: "festive-collection",
    description:
      "Embroidered kurtas, shalwar kameez and waistcoats styled for festive gatherings.",
    cover: "festive",
    season: "Festive",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "published",
    visibility: "visible",
    featured: false,
    productCount: 46,
    categories: ["Shalwar Kameez", "Kurtas", "Waistcoats"],
    scheduledFor: null,
    revenue: 4380000,
    views: 39100,
    conversion: 4.1,
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-06-20T09:00:00Z",
    activity: [
      { id: "a1", label: "Banner refreshed", timestamp: "2026-06-20T09:00:00Z" },
    ],
  },
  {
    id: "col_08",
    name: "Editor's Picks",
    subtitle: "Curated by our creative director",
    slug: "editors-picks",
    description:
      "A rotating, hand-selected edit spotlighting standout pieces and unexpected pairings.",
    cover: "editor",
    season: "Evergreen",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "draft",
    visibility: "hidden",
    featured: false,
    productCount: 12,
    categories: ["Western Suiting", "Sherwanis"],
    scheduledFor: null,
    revenue: 0,
    views: 0,
    conversion: 0,
    createdAt: "2026-06-26T09:00:00Z",
    updatedAt: "2026-06-30T09:00:00Z",
    activity: [
      { id: "a1", label: "Draft created", timestamp: "2026-06-26T09:00:00Z" },
    ],
  },
  {
    id: "col_09",
    name: "Summer Linen",
    subtitle: "Featherweight tailoring for warm days",
    slug: "summer-linen",
    description:
      "Breathable linen suiting and separates in sand, ivory and stone — built for heat and humidity.",
    cover: "summer",
    season: "Summer 2026",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "scheduled",
    visibility: "hidden",
    featured: false,
    productCount: 19,
    categories: ["Western Suiting", "Kurtas"],
    scheduledFor: "2026-08-15T09:00:00Z",
    revenue: 0,
    views: 0,
    conversion: 0,
    createdAt: "2026-06-30T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
    activity: [
      { id: "a1", label: "Scheduled for Aug 15", timestamp: "2026-07-01T09:00:00Z" },
    ],
  },
  {
    id: "col_10",
    name: "Limited Edition",
    subtitle: "Numbered, archival, never restocked",
    slug: "limited-edition",
    description:
      "One-time capsule runs in rare cloths — each piece numbered and retired once sold through.",
    cover: "limited",
    season: "Limited Edition",
    type: "manual",
    ruleMatch: "all",
    rules: [],
    status: "archived",
    visibility: "hidden",
    featured: false,
    productCount: 8,
    categories: ["Sherwanis", "Western Suiting"],
    scheduledFor: null,
    revenue: 3120000,
    views: 18700,
    conversion: 7.4,
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-05-30T09:00:00Z",
    activity: [
      { id: "a1", label: "Archived (sold out)", timestamp: "2026-05-30T09:00:00Z" },
    ],
  },
]

export const featuredCollections = collections.filter((c) => c.featured)
