import type { CustomerDetail, OrderMeasurements } from "@/types"

/** Measurement helper — sensible defaults so each profile only overrides what differs. */
const M = (m: Partial<OrderMeasurements>): OrderMeasurements => ({
  chest: 40,
  waist: 34,
  hips: 40,
  shoulder: 18,
  sleeve: 25,
  neck: 16,
  inseam: 32,
  height: 70,
  referenceImages: [],
  ...m,
})

export const customerDetails: CustomerDetail[] = [
  {
    id: "cus_01",
    reference: "CUST-2041",
    name: "Ahsan Raza",
    initials: "AR",
    email: "ahsan.raza@gmail.com",
    phone: "+92 300 1234567",
    country: "Pakistan",
    flag: "🇵🇰",
    city: "Lahore",
    status: "active",
    vip: true,
    tier: "gold",
    joinedAt: "2023-03-14T09:00:00Z",
    lastOrderAt: "2026-07-04T08:10:00Z",
    ordersCount: 7,
    lifetimeValue: 486000,
    avgOrderValue: 69428,
    yearsCustomer: 3,
    tailoringClient: true,
    weddingClient: true,
    international: false,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: true,
    preferredTailor: "Master Yousuf",
    note: "Groom this season — very particular about collar embroidery. Handle personally.",
    measurementProfiles: [
      {
        id: "mp_01a",
        name: "Wedding 2026",
        fit: "wedding",
        updatedAt: "2026-07-05T14:00:00Z",
        measurements: M({
          chest: 42,
          waist: 36,
          shoulder: 18.5,
          sleeve: 25.5,
          neck: 16.5,
          height: 71,
          notes: "Slightly tapered waist, extra sleeve length.",
          referenceImages: ["maroon", "charcoal"],
        }),
      },
      {
        id: "mp_01b",
        name: "Regular Fit",
        fit: "regular",
        updatedAt: "2025-11-02T10:00:00Z",
        measurements: M({ chest: 42, waist: 37, height: 71 }),
      },
    ],
    addresses: [
      {
        id: "ad_01",
        label: "Home",
        type: "shipping",
        line: "House 24, DHA Phase 5",
        city: "Lahore",
        country: "Pakistan",
        flag: "🇵🇰",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Jamawar",
      color: "Ivory",
      fit: "wedding",
      categories: ["Sherwanis", "Waistcoats"],
      collections: ["Wedding Collection"],
      tailor: "Master Yousuf",
    },
    orderHistory: [
      {
        id: "oh_01",
        reference: "TMK-10482",
        date: "2026-07-04T08:10:00Z",
        total: 42000,
        stage: "tailoring",
        type: "custom_tailoring",
        itemName: "Ivory Embroidered Sherwani",
        image: "ivory",
      },
      {
        id: "oh_02",
        reference: "TMK-10310",
        date: "2025-12-18T08:10:00Z",
        total: 58000,
        stage: "delivered",
        type: "custom_tailoring",
        itemName: "Maroon Bespoke Sherwani",
        image: "maroon",
      },
      {
        id: "oh_03",
        reference: "TMK-10188",
        date: "2025-06-02T08:10:00Z",
        total: 22000,
        stage: "delivered",
        type: "ready_to_wear",
        itemName: "Charcoal Waistcoat",
        image: "charcoal",
      },
    ],
    activity: [
      { id: "ca1", type: "order", title: "Placed order TMK-10482", meta: "Ivory Sherwani · PKR 42,000", at: "2026-07-04T08:10:00Z" },
      { id: "ca2", type: "measurement", title: "Updated Wedding 2026 profile", meta: "by Sana (Ops)", at: "2026-07-05T14:00:00Z" },
      { id: "ca3", type: "whatsapp", title: "WhatsApp: fitting confirmation", meta: "outbound", at: "2026-07-06T09:30:00Z" },
    ],
    timeline: [
      { id: "cm1", kind: "registered", label: "Joined T-Mark Apparel", at: "2023-03-14T09:00:00Z" },
      { id: "cm2", kind: "first_order", label: "First order placed", at: "2023-04-02T09:00:00Z" },
      { id: "cm3", kind: "measurements", label: "Saved first measurement profile", at: "2023-04-10T09:00:00Z" },
      { id: "cm4", kind: "vip", label: "Reached Gold VIP tier", at: "2024-09-01T09:00:00Z" },
      { id: "cm5", kind: "wedding", label: "Wedding order placed", at: "2026-07-04T08:10:00Z" },
    ],
  },
  {
    id: "cus_02",
    reference: "CUST-1180",
    name: "Imran Yousaf",
    initials: "IY",
    email: "imran.y@gmail.com",
    phone: "+44 7700 900123",
    country: "United Kingdom",
    flag: "🇬🇧",
    city: "London",
    status: "active",
    vip: true,
    tier: "platinum",
    joinedAt: "2021-05-20T09:00:00Z",
    lastOrderAt: "2026-07-01T14:30:00Z",
    ordersCount: 9,
    lifetimeValue: 612000,
    avgOrderValue: 68000,
    yearsCustomer: 5,
    tailoringClient: true,
    weddingClient: false,
    international: true,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: false,
    preferredTailor: "Master Iqbal",
    note: "Platinum client since 2021. Knows exactly what he wants — trusts the atelier's judgement.",
    measurementProfiles: [
      {
        id: "mp_02a",
        name: "Classic Fit",
        fit: "classic",
        updatedAt: "2026-06-20T10:00:00Z",
        measurements: M({
          chest: 41,
          waist: 35,
          shoulder: 18,
          sleeve: 26,
          neck: 16,
          inseam: 33,
          height: 72,
          notes: "Working cuffs, slight trouser break.",
          referenceImages: ["navy"],
        }),
      },
    ],
    addresses: [
      {
        id: "ad_02",
        label: "Residence",
        type: "shipping",
        line: "42 Baker Street",
        city: "London",
        country: "United Kingdom",
        flag: "🇬🇧",
        isDefault: true,
      },
      {
        id: "ad_02b",
        label: "Billing",
        type: "billing",
        line: "42 Baker Street",
        city: "London",
        country: "United Kingdom",
        flag: "🇬🇧",
        isDefault: false,
      },
    ],
    preferences: {
      fabric: "Wool Blend",
      color: "Navy",
      fit: "classic",
      categories: ["Western Suits", "Prince Coats"],
      collections: ["Best Sellers"],
      tailor: "Master Iqbal",
    },
    orderHistory: [
      {
        id: "oh_04",
        reference: "TMK-10476",
        date: "2026-07-01T14:30:00Z",
        total: 46500,
        stage: "ready",
        type: "custom_tailoring",
        itemName: "Navy Three-Piece Bespoke Suit",
        image: "navy",
      },
      {
        id: "oh_05",
        reference: "TMK-10201",
        date: "2025-08-14T14:30:00Z",
        total: 72000,
        stage: "delivered",
        type: "custom_tailoring",
        itemName: "Charcoal Dinner Suit",
        image: "charcoal",
      },
    ],
    activity: [
      { id: "ca4", type: "order", title: "Placed order TMK-10476", meta: "Navy Bespoke Suit · PKR 46,500", at: "2026-07-01T14:30:00Z" },
      { id: "ca5", type: "email", title: "Email: dispatch update sent", meta: "outbound", at: "2026-07-06T11:00:00Z" },
    ],
    timeline: [
      { id: "cm6", kind: "registered", label: "Joined T-Mark Apparel", at: "2021-05-20T09:00:00Z" },
      { id: "cm7", kind: "first_order", label: "First bespoke commission", at: "2021-06-11T09:00:00Z" },
      { id: "cm8", kind: "vip", label: "Reached Platinum VIP tier", at: "2023-02-01T09:00:00Z" },
      { id: "cm9", kind: "purchase", label: "9th order placed", at: "2026-07-01T14:30:00Z" },
    ],
  },
  {
    id: "cus_03",
    reference: "CUST-1042",
    name: "Yousaf Nawaz",
    initials: "YN",
    email: "yousaf.n@gmail.com",
    phone: "+974 5512 3456",
    country: "Qatar",
    flag: "🇶🇦",
    city: "Doha",
    status: "active",
    vip: true,
    tier: "platinum",
    joinedAt: "2020-11-02T09:00:00Z",
    lastOrderAt: "2026-06-20T09:00:00Z",
    ordersCount: 8,
    lifetimeValue: 540000,
    avgOrderValue: 67500,
    yearsCustomer: 6,
    tailoringClient: true,
    weddingClient: true,
    international: true,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: false,
    preferredTailor: "Master Yousuf",
    note: "Longest-standing international VIP. Send seasonal lookbook first.",
    measurementProfiles: [
      {
        id: "mp_03a",
        name: "Regular Fit",
        fit: "regular",
        updatedAt: "2026-05-01T10:00:00Z",
        measurements: M({
          chest: 44,
          waist: 39,
          shoulder: 19.5,
          sleeve: 26.5,
          neck: 17.5,
          height: 75,
          referenceImages: ["maroon"],
        }),
      },
    ],
    addresses: [
      {
        id: "ad_03",
        label: "Villa",
        type: "shipping",
        line: "West Bay",
        city: "Doha",
        country: "Qatar",
        flag: "🇶🇦",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Jamawar",
      color: "Maroon",
      fit: "regular",
      categories: ["Sherwanis"],
      collections: ["Wedding Collection", "Limited Edition"],
      tailor: "Master Yousuf",
    },
    orderHistory: [
      {
        id: "oh_06",
        reference: "TMK-10468",
        date: "2026-06-20T09:00:00Z",
        total: 72000,
        stage: "delivered",
        type: "custom_tailoring",
        itemName: "Maroon Bespoke Sherwani",
        image: "maroon",
      },
    ],
    activity: [
      { id: "ca6", type: "order", title: "Placed order TMK-10468", meta: "Maroon Sherwani · PKR 72,000", at: "2026-06-20T09:00:00Z" },
      { id: "ca7", type: "status", title: "Order delivered ahead of schedule", meta: "DHL Express", at: "2026-07-01T12:00:00Z" },
    ],
    timeline: [
      { id: "cm10", kind: "registered", label: "Joined T-Mark Apparel", at: "2020-11-02T09:00:00Z" },
      { id: "cm11", kind: "vip", label: "Reached Platinum VIP tier", at: "2022-04-01T09:00:00Z" },
      { id: "cm12", kind: "purchase", label: "Latest order delivered", at: "2026-07-01T12:00:00Z" },
    ],
  },
  {
    id: "cus_04",
    reference: "CUST-1990",
    name: "Omar Farooq",
    initials: "OF",
    email: "omar.farooq@gmail.com",
    phone: "+971 50 4567890",
    country: "UAE",
    flag: "🇦🇪",
    city: "Dubai",
    status: "active",
    vip: true,
    tier: "gold",
    joinedAt: "2022-09-10T09:00:00Z",
    lastOrderAt: "2026-07-03T11:05:00Z",
    ordersCount: 5,
    lifetimeValue: 214000,
    avgOrderValue: 42800,
    yearsCustomer: 4,
    tailoringClient: false,
    weddingClient: false,
    international: true,
    repeatBuyer: true,
    hasMeasurements: false,
    followUp: false,
    preferredTailor: null,
    note: "Prefers ready-to-wear, values fast international shipping.",
    measurementProfiles: [],
    addresses: [
      {
        id: "ad_04",
        label: "Home",
        type: "shipping",
        line: "Villa 12, Jumeirah 1",
        city: "Dubai",
        country: "UAE",
        flag: "🇦🇪",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Linen",
      color: "Sand",
      fit: "regular",
      categories: ["Shalwar Kameez", "Kurtas"],
      collections: ["Summer Collection"],
      tailor: null,
    },
    orderHistory: [
      {
        id: "oh_07",
        reference: "TMK-10479",
        date: "2026-07-03T11:05:00Z",
        total: 15600,
        stage: "shipped",
        type: "ready_to_wear",
        itemName: "Sand Linen Shalwar Kameez",
        image: "sand",
      },
    ],
    activity: [
      { id: "ca8", type: "order", title: "Placed order TMK-10479", meta: "Sand Shalwar Kameez · PKR 15,600", at: "2026-07-03T11:05:00Z" },
    ],
    timeline: [
      { id: "cm13", kind: "registered", label: "Joined T-Mark Apparel", at: "2022-09-10T09:00:00Z" },
      { id: "cm14", kind: "vip", label: "Reached Gold VIP tier", at: "2024-01-15T09:00:00Z" },
      { id: "cm15", kind: "purchase", label: "Latest purchase", at: "2026-07-03T11:05:00Z" },
    ],
  },
  {
    id: "cus_05",
    reference: "CUST-1051",
    name: "Abdullah Al-Rashid",
    initials: "AA",
    email: "a.alrashid@gmail.com",
    phone: "+966 55 1234567",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    city: "Riyadh",
    status: "active",
    vip: true,
    tier: "gold",
    joinedAt: "2022-01-08T09:00:00Z",
    lastOrderAt: "2026-07-05T10:00:00Z",
    ordersCount: 6,
    lifetimeValue: 331000,
    avgOrderValue: 55166,
    yearsCustomer: 4,
    tailoringClient: true,
    weddingClient: true,
    international: true,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: true,
    preferredTailor: "Master Rehman",
    note: "Wedding on 30 July — half advance paid, awaiting final measurement confirmation.",
    measurementProfiles: [
      {
        id: "mp_05a",
        name: "Wedding 2026",
        fit: "wedding",
        updatedAt: "2026-07-06T09:00:00Z",
        measurements: M({
          chest: 43,
          waist: 37,
          shoulder: 19,
          sleeve: 26,
          neck: 17,
          height: 74,
          notes: "High collar, gold thread accents on cuffs.",
          referenceImages: ["ivory", "sand"],
        }),
      },
    ],
    addresses: [
      {
        id: "ad_05",
        label: "Home",
        type: "shipping",
        line: "King Fahd Rd, Al Olaya",
        city: "Riyadh",
        country: "Saudi Arabia",
        flag: "🇸🇦",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Jamawar",
      color: "Ivory",
      fit: "wedding",
      categories: ["Sherwanis", "Prince Coats"],
      collections: ["Wedding Collection"],
      tailor: "Master Rehman",
    },
    orderHistory: [
      {
        id: "oh_08",
        reference: "TMK-10474",
        date: "2026-07-05T10:00:00Z",
        total: 68000,
        stage: "measurements",
        type: "made_to_measure",
        itemName: "Ivory Wedding Sherwani",
        image: "ivory",
      },
    ],
    activity: [
      { id: "ca9", type: "measurement", title: "Received measurements", meta: "by Master Rehman", at: "2026-07-06T09:00:00Z" },
      { id: "ca10", type: "order", title: "Placed order TMK-10474", meta: "Wedding Sherwani · PKR 68,000", at: "2026-07-05T10:00:00Z" },
    ],
    timeline: [
      { id: "cm16", kind: "registered", label: "Joined T-Mark Apparel", at: "2022-01-08T09:00:00Z" },
      { id: "cm17", kind: "vip", label: "Reached Gold VIP tier", at: "2023-11-01T09:00:00Z" },
      { id: "cm18", kind: "wedding", label: "Wedding order in production", at: "2026-07-05T10:00:00Z" },
    ],
  },
  {
    id: "cus_06",
    reference: "CUST-1203",
    name: "Usman Tariq",
    initials: "UT",
    email: "usman.tariq@gmail.com",
    phone: "+92 303 4567890",
    country: "Pakistan",
    flag: "🇵🇰",
    city: "Lahore",
    status: "active",
    vip: false,
    tier: "member",
    joinedAt: "2024-02-19T09:00:00Z",
    lastOrderAt: "2026-06-12T09:00:00Z",
    ordersCount: 9,
    lifetimeValue: 231400,
    avgOrderValue: 25711,
    yearsCustomer: 2,
    tailoringClient: false,
    weddingClient: false,
    international: false,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: false,
    preferredTailor: null,
    note: null,
    measurementProfiles: [
      {
        id: "mp_06a",
        name: "Slim Fit",
        fit: "slim",
        updatedAt: "2026-03-10T10:00:00Z",
        measurements: M({ chest: 38, waist: 31, shoulder: 17, height: 69 }),
      },
    ],
    addresses: [
      {
        id: "ad_06",
        label: "Home",
        type: "shipping",
        line: "House 5, Model Town",
        city: "Lahore",
        country: "Pakistan",
        flag: "🇵🇰",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Egyptian Cotton",
      color: "Navy",
      fit: "slim",
      categories: ["Kurtas", "Shalwar Kameez"],
      collections: ["New Arrivals"],
      tailor: null,
    },
    orderHistory: [
      {
        id: "oh_09",
        reference: "TMK-10402",
        date: "2026-06-12T09:00:00Z",
        total: 18900,
        stage: "delivered",
        type: "ready_to_wear",
        itemName: "Navy Formal Kurta",
        image: "navy",
      },
    ],
    activity: [
      { id: "ca11", type: "order", title: "Placed order TMK-10402", meta: "Navy Kurta · PKR 18,900", at: "2026-06-12T09:00:00Z" },
    ],
    timeline: [
      { id: "cm19", kind: "registered", label: "Joined T-Mark Apparel", at: "2024-02-19T09:00:00Z" },
      { id: "cm20", kind: "purchase", label: "9th order placed", at: "2026-06-12T09:00:00Z" },
    ],
  },
  {
    id: "cus_07",
    reference: "CUST-2088",
    name: "Michael Chen",
    initials: "MC",
    email: "m.chen@gmail.com",
    phone: "+1 415 555 0147",
    country: "United States",
    flag: "🇺🇸",
    city: "San Francisco",
    status: "active",
    vip: false,
    tier: "member",
    joinedAt: "2026-07-05T20:00:00Z",
    lastOrderAt: "2026-07-05T20:00:00Z",
    ordersCount: 1,
    lifetimeValue: 34000,
    avgOrderValue: 34000,
    yearsCustomer: 0,
    tailoringClient: false,
    weddingClient: true,
    international: true,
    repeatBuyer: false,
    hasMeasurements: false,
    followUp: true,
    preferredTailor: null,
    note: "First-time international customer — attending a friend's wedding. Great onboarding opportunity.",
    measurementProfiles: [],
    addresses: [
      {
        id: "ad_07",
        label: "Home",
        type: "shipping",
        line: "500 Market St",
        city: "San Francisco",
        country: "United States",
        flag: "🇺🇸",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Raw Silk",
      color: "Emerald",
      fit: "regular",
      categories: ["Sherwanis"],
      collections: ["Wedding Collection"],
      tailor: null,
    },
    orderHistory: [
      {
        id: "oh_10",
        reference: "TMK-10469",
        date: "2026-07-05T20:00:00Z",
        total: 34000,
        stage: "confirmed",
        type: "ready_to_wear",
        itemName: "Emerald Silk Sherwani",
        image: "emerald",
      },
    ],
    activity: [
      { id: "ca12", type: "registered", title: "Created account", meta: "web signup", at: "2026-07-05T19:50:00Z" },
      { id: "ca13", type: "order", title: "Placed first order TMK-10469", meta: "Emerald Sherwani · PKR 34,000", at: "2026-07-05T20:00:00Z" },
    ],
    timeline: [
      { id: "cm21", kind: "registered", label: "Joined T-Mark Apparel", at: "2026-07-05T19:50:00Z" },
      { id: "cm22", kind: "first_order", label: "First order placed", at: "2026-07-05T20:00:00Z" },
    ],
  },
  {
    id: "cus_08",
    reference: "CUST-1777",
    name: "Kamran Shah",
    initials: "KS",
    email: "kamran.shah@gmail.com",
    phone: "+1 416 555 0192",
    country: "Canada",
    flag: "🇨🇦",
    city: "Toronto",
    status: "active",
    vip: false,
    tier: "member",
    joinedAt: "2024-10-01T09:00:00Z",
    lastOrderAt: "2026-07-02T09:00:00Z",
    ordersCount: 3,
    lifetimeValue: 176000,
    avgOrderValue: 58666,
    yearsCustomer: 2,
    tailoringClient: true,
    weddingClient: false,
    international: true,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: false,
    preferredTailor: "Master Iqbal",
    note: null,
    measurementProfiles: [
      {
        id: "mp_08a",
        name: "Classic Fit",
        fit: "classic",
        updatedAt: "2026-02-14T10:00:00Z",
        measurements: M({
          chest: 42,
          waist: 36,
          shoulder: 18.5,
          sleeve: 25.5,
          inseam: 32,
          height: 71,
          notes: "Half-canvas construction preferred.",
          referenceImages: ["charcoal"],
        }),
      },
    ],
    addresses: [
      {
        id: "ad_08",
        label: "Home",
        type: "shipping",
        line: "88 Yonge Street",
        city: "Toronto",
        country: "Canada",
        flag: "🇨🇦",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Wool Blend",
      color: "Charcoal",
      fit: "classic",
      categories: ["Western Suits"],
      collections: ["Best Sellers"],
      tailor: "Master Iqbal",
    },
    orderHistory: [
      {
        id: "oh_11",
        reference: "TMK-10472",
        date: "2026-07-02T09:00:00Z",
        total: 44000,
        stage: "quality_check",
        type: "custom_tailoring",
        itemName: "Charcoal Bespoke Two-Piece",
        image: "charcoal",
      },
    ],
    activity: [
      { id: "ca14", type: "order", title: "Placed order TMK-10472", meta: "Charcoal Two-Piece · PKR 44,000", at: "2026-07-02T09:00:00Z" },
    ],
    timeline: [
      { id: "cm23", kind: "registered", label: "Joined T-Mark Apparel", at: "2024-10-01T09:00:00Z" },
      { id: "cm24", kind: "measurements", label: "Saved Classic Fit profile", at: "2024-10-20T09:00:00Z" },
      { id: "cm25", kind: "purchase", label: "Latest bespoke order", at: "2026-07-02T09:00:00Z" },
    ],
  },
  {
    id: "cus_09",
    reference: "CUST-1120",
    name: "Bilal Khan",
    initials: "BK",
    email: "bilal.khan@outlook.com",
    phone: "+92 301 2345678",
    country: "Pakistan",
    flag: "🇵🇰",
    city: "Karachi",
    status: "active",
    vip: false,
    tier: "member",
    joinedAt: "2025-06-29T09:00:00Z",
    lastOrderAt: "2026-07-04T06:40:00Z",
    ordersCount: 2,
    lifetimeValue: 61000,
    avgOrderValue: 30500,
    yearsCustomer: 1,
    tailoringClient: false,
    weddingClient: false,
    international: false,
    repeatBuyer: true,
    hasMeasurements: false,
    followUp: false,
    preferredTailor: null,
    note: null,
    measurementProfiles: [],
    addresses: [
      {
        id: "ad_09",
        label: "Home",
        type: "shipping",
        line: "Flat 7B, Clifton Block 4",
        city: "Karachi",
        country: "Pakistan",
        flag: "🇵🇰",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Wool Blend",
      color: "Charcoal",
      fit: "regular",
      categories: ["Waistcoats", "Kurtas"],
      collections: ["New Arrivals"],
      tailor: null,
    },
    orderHistory: [
      {
        id: "oh_12",
        reference: "TMK-10481",
        date: "2026-07-04T06:40:00Z",
        total: 18900,
        stage: "confirmed",
        type: "ready_to_wear",
        itemName: "Charcoal Wool Waistcoat",
        image: "charcoal",
      },
    ],
    activity: [
      { id: "ca15", type: "order", title: "Placed order TMK-10481", meta: "Waistcoat + Kurta · PKR 18,900", at: "2026-07-04T06:40:00Z" },
    ],
    timeline: [
      { id: "cm26", kind: "registered", label: "Joined T-Mark Apparel", at: "2025-06-29T09:00:00Z" },
      { id: "cm27", kind: "first_order", label: "First order placed", at: "2025-07-10T09:00:00Z" },
    ],
  },
  {
    id: "cus_10",
    reference: "CUST-0904",
    name: "Zeeshan Ali",
    initials: "ZA",
    email: "zeeshan.ali@gmail.com",
    phone: "+92 305 6789012",
    country: "Pakistan",
    flag: "🇵🇰",
    city: "Multan",
    status: "inactive",
    vip: false,
    tier: "member",
    joinedAt: "2023-08-15T09:00:00Z",
    lastOrderAt: "2025-01-20T09:00:00Z",
    ordersCount: 1,
    lifetimeValue: 9800,
    avgOrderValue: 9800,
    yearsCustomer: 3,
    tailoringClient: false,
    weddingClient: false,
    international: false,
    repeatBuyer: false,
    hasMeasurements: false,
    followUp: true,
    preferredTailor: null,
    note: "Cancelled last order over sizing. Worth a re-engagement offer.",
    measurementProfiles: [],
    addresses: [
      {
        id: "ad_10",
        label: "Home",
        type: "shipping",
        line: "House 41, Cantt",
        city: "Multan",
        country: "Pakistan",
        flag: "🇵🇰",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Velvet",
      color: "Maroon",
      fit: "regular",
      categories: ["Waistcoats"],
      collections: ["Festive"],
      tailor: null,
    },
    orderHistory: [
      {
        id: "oh_13",
        reference: "TMK-10120",
        date: "2025-01-20T09:00:00Z",
        total: 9800,
        stage: "cancelled",
        type: "ready_to_wear",
        itemName: "Maroon Velvet Waistcoat",
        image: "maroon",
      },
    ],
    activity: [
      { id: "ca16", type: "status", title: "Order cancelled", meta: "sizing issue", at: "2025-01-20T12:40:00Z" },
    ],
    timeline: [
      { id: "cm28", kind: "registered", label: "Joined T-Mark Apparel", at: "2023-08-15T09:00:00Z" },
      { id: "cm29", kind: "first_order", label: "First order (cancelled)", at: "2025-01-20T09:00:00Z" },
    ],
  },
  {
    id: "cus_11",
    reference: "CUST-1466",
    name: "Ali Raza Bukhari",
    initials: "AB",
    email: "ali.bukhari@gmail.com",
    phone: "+61 4 1234 5678",
    country: "Australia",
    flag: "🇦🇺",
    city: "Sydney",
    status: "active",
    vip: false,
    tier: "member",
    joinedAt: "2024-05-30T09:00:00Z",
    lastOrderAt: "2026-07-01T08:00:00Z",
    ordersCount: 2,
    lifetimeValue: 92000,
    avgOrderValue: 46000,
    yearsCustomer: 2,
    tailoringClient: true,
    weddingClient: false,
    international: true,
    repeatBuyer: true,
    hasMeasurements: true,
    followUp: false,
    preferredTailor: "Master Nadeem",
    note: null,
    measurementProfiles: [
      {
        id: "mp_11a",
        name: "Regular Fit",
        fit: "regular",
        updatedAt: "2026-06-25T10:00:00Z",
        measurements: M({
          chest: 41,
          waist: 35,
          shoulder: 18,
          sleeve: 25.5,
          inseam: 33,
          height: 72,
          notes: "Ticket pocket, side adjusters.",
          referenceImages: ["charcoal", "navy"],
        }),
      },
    ],
    addresses: [
      {
        id: "ad_11",
        label: "Home",
        type: "shipping",
        line: "17 George St",
        city: "Sydney",
        country: "Australia",
        flag: "🇦🇺",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Wool Blend",
      color: "Charcoal",
      fit: "regular",
      categories: ["Western Suits"],
      collections: ["Best Sellers"],
      tailor: "Master Nadeem",
    },
    orderHistory: [
      {
        id: "oh_14",
        reference: "TMK-10466",
        date: "2026-07-01T08:00:00Z",
        total: 47000,
        stage: "tailoring",
        type: "made_to_measure",
        itemName: "Charcoal MTM Three-Piece",
        image: "charcoal",
      },
    ],
    activity: [
      { id: "ca17", type: "order", title: "Placed order TMK-10466", meta: "MTM Three-Piece · PKR 47,000", at: "2026-07-01T08:00:00Z" },
    ],
    timeline: [
      { id: "cm30", kind: "registered", label: "Joined T-Mark Apparel", at: "2024-05-30T09:00:00Z" },
      { id: "cm31", kind: "measurements", label: "Saved Regular Fit profile", at: "2024-06-18T09:00:00Z" },
      { id: "cm32", kind: "purchase", label: "Latest MTM order", at: "2026-07-01T08:00:00Z" },
    ],
  },
  {
    id: "cus_12",
    reference: "CUST-0788",
    name: "Noman Siddiqui",
    initials: "NS",
    email: "noman.s@gmail.com",
    phone: "+92 312 3456789",
    country: "Pakistan",
    flag: "🇵🇰",
    city: "Quetta",
    status: "inactive",
    vip: false,
    tier: "member",
    joinedAt: "2023-04-11T09:00:00Z",
    lastOrderAt: "2026-06-24T10:00:00Z",
    ordersCount: 2,
    lifetimeValue: 21000,
    avgOrderValue: 10500,
    yearsCustomer: 3,
    tailoringClient: false,
    weddingClient: false,
    international: false,
    repeatBuyer: true,
    hasMeasurements: false,
    followUp: true,
    preferredTailor: null,
    note: "Returned last order — flag listing photos. Offer a discount to win back.",
    measurementProfiles: [],
    addresses: [
      {
        id: "ad_12",
        label: "Home",
        type: "shipping",
        line: "House 5, Jinnah Road",
        city: "Quetta",
        country: "Pakistan",
        flag: "🇵🇰",
        isDefault: true,
      },
    ],
    preferences: {
      fabric: "Wool Blend",
      color: "Black",
      fit: "regular",
      categories: ["Waistcoats"],
      collections: ["Festive"],
      tailor: null,
    },
    orderHistory: [
      {
        id: "oh_15",
        reference: "TMK-10465",
        date: "2026-06-24T10:00:00Z",
        total: 21000,
        stage: "refunded",
        type: "ready_to_wear",
        itemName: "Black Formal Waistcoat",
        image: "black",
      },
    ],
    activity: [
      { id: "ca18", type: "status", title: "Order refunded", meta: "returned — photos mismatch", at: "2026-07-03T11:00:00Z" },
    ],
    timeline: [
      { id: "cm33", kind: "registered", label: "Joined T-Mark Apparel", at: "2023-04-11T09:00:00Z" },
      { id: "cm34", kind: "purchase", label: "Last order (refunded)", at: "2026-06-24T10:00:00Z" },
    ],
  },
]
