import type { HomepageDraft, HomepageRevision } from "@/types"

export const homepageDraft: HomepageDraft = {
  sections: [
    {
      id: "sec_hero",
      type: "hero",
      name: "Wedding Season Hero",
      visible: true,
      locked: false,
      settings: {
        title: "For the day you'll never forget",
        subtitle: "The 2026 Wedding Collection — bespoke sherwanis & prince coats",
        cta: "Explore the Wedding Edit",
        ctaLink: "/collections/wedding",
        cover: "wedding",
        overlay: "medium",
        alignment: "left",
        height: "tall",
        buttonStyle: "solid",
        animation: "fade",
      },
    },
    {
      id: "sec_categories",
      type: "featured_categories",
      name: "Shop by Category",
      visible: true,
      locked: false,
      settings: {
        title: "Shop by category",
        layout: "grid",
        columns: 3,
        spacing: "comfortable",
        background: "surface",
      },
    },
    {
      id: "sec_collections",
      type: "featured_collections",
      name: "Curated Collections",
      visible: true,
      locked: false,
      settings: {
        title: "Curated for the season",
        collection: "Wedding Collection",
        layout: "carousel",
        itemCount: 4,
        cta: "View collection",
        background: "muted",
        spacing: "spacious",
      },
    },
    {
      id: "sec_products",
      type: "featured_products",
      name: "Featured Products",
      visible: true,
      locked: false,
      settings: {
        title: "Hand-picked for you",
        itemCount: 4,
        layout: "grid",
        cta: "Shop all",
        spacing: "comfortable",
      },
    },
    {
      id: "sec_tailoring",
      type: "custom_tailoring",
      name: "Custom Tailoring",
      visible: true,
      locked: false,
      settings: {
        title: "Made to measure, made for you",
        subtitle: "Book a private fitting with our master tailors and craft a garment that's entirely your own.",
        cta: "Book a fitting",
        ctaLink: "/custom-tailoring",
        background: "ink",
        spacing: "spacious",
      },
    },
    {
      id: "sec_story",
      type: "brand_story",
      name: "Brand Story",
      visible: true,
      locked: false,
      settings: {
        title: "Tailored since 1998",
        subtitle: "Three generations of craftsmanship, from Lahore to the world.",
        cover: "editor",
        alignment: "left",
        background: "surface",
      },
    },
    {
      id: "sec_testimonials",
      type: "testimonials",
      name: "Testimonials",
      visible: true,
      locked: false,
      settings: {
        title: "In their words",
        layout: "grid",
        itemCount: 3,
        background: "muted",
      },
    },
    {
      id: "sec_instagram",
      type: "instagram",
      name: "Instagram Feed",
      visible: false,
      locked: false,
      settings: {
        title: "Follow the atelier",
        handle: "@tmarkapparel",
        columns: 4,
        spacing: "tight",
      },
    },
    {
      id: "sec_newsletter",
      type: "newsletter",
      name: "Newsletter",
      visible: true,
      locked: false,
      settings: {
        title: "Join the atelier list",
        subtitle: "Early access to new collections and private events.",
        cta: "Subscribe",
        background: "surface",
        alignment: "center",
      },
    },
    {
      id: "sec_footer",
      type: "footer",
      name: "Footer",
      visible: true,
      locked: true,
      settings: {
        title: "Luxury menswear, tailored worldwide",
        background: "ink",
      },
    },
  ],
  globals: {
    announcementEnabled: true,
    announcementText: "Complimentary worldwide shipping this Eid — ends 11 July",
    stickyHeader: true,
    featuredCollection: "Wedding Collection",
    theme: "editorial",
    seasonalTheme: "Wedding 2026",
    newsletterEnabled: true,
    instagramHandle: "@tmarkapparel",
    footerNote: "© 2026 T-Mark Apparel. All rights reserved.",
  },
}

export const homepageRevisions: HomepageRevision[] = [
  { id: "rev_5", label: "Enabled wedding hero + reordered collections", author: "Sana (Ops)", at: "2026-07-06T09:20:00Z", published: true },
  { id: "rev_4", label: "Added custom tailoring section", author: "Owner", at: "2026-07-02T14:00:00Z", published: true },
  { id: "rev_3", label: "Hid Instagram feed for summer", author: "Sana (Ops)", at: "2026-06-28T11:30:00Z", published: false },
  { id: "rev_2", label: "Updated announcement bar", author: "Sana (Ops)", at: "2026-06-25T08:15:00Z", published: true },
  { id: "rev_1", label: "Initial homepage layout", author: "Owner", at: "2026-06-01T10:00:00Z", published: true },
]
