import { ORDER_PIPELINE, stageIndex } from "@/lib/constants"
import type {
  OrderDetail,
  OrderMeasurements,
  OrderStage,
  OrderTimelineStep,
} from "@/types"

/**
 * Fills the production timeline up to `completed` stages, spacing each stage
 * ~22h apart from the order's creation. Keeping this here means every order's
 * timeline is internally consistent with its current stage.
 */
function buildTimeline(base: string, completed: number): OrderTimelineStep[] {
  const start = new Date(base).getTime()
  return ORDER_PIPELINE.map((stage, i) => ({
    stage,
    at: i < completed ? new Date(start + i * 22 * 3_600_000).toISOString() : null,
  }))
}

/** For happy-path orders the timeline is derived from the current stage. */
function timelineFor(stage: OrderStage, base: string): OrderTimelineStep[] {
  const idx = stageIndex(stage)
  return buildTimeline(base, idx >= 0 ? idx + 1 : 2)
}

const M = (m: Partial<OrderMeasurements>): OrderMeasurements => ({
  chest: 40,
  waist: 34,
  hips: 40,
  shoulder: 18,
  sleeve: 25,
  neck: 16,
  inseam: 32,
  height: 70,
  referenceImages: [],
  ...m,
})

export const orderDetails: OrderDetail[] = [
  {
    id: "ord_01",
    reference: "TMK-10482",
    type: "custom_tailoring",
    stage: "tailoring",
    priority: "urgent",
    customer: {
      id: "cus_01",
      name: "Ahsan Raza",
      initials: "AR",
      email: "ahsan.raza@gmail.com",
      phone: "+92 300 1234567",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Lahore",
      addressLine: "House 24, DHA Phase 5, Lahore",
      vip: true,
      ordersCount: 7,
      lifetimeValue: 486000,
    },
    items: [
      {
        id: "li_01",
        name: "Ivory Embroidered Sherwani",
        image: "ivory",
        type: "custom_tailoring",
        fabric: "Jamawar",
        color: "Ivory",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 42000,
      },
    ],
    itemCount: 1,
    total: 42000,
    payment: {
      method: "Bank Transfer",
      status: "paid",
      transactionId: "TXN-9F2A81",
      subtotal: 42000,
      shipping: 0,
      discount: 0,
      tax: 0,
      total: 42000,
      paid: 42000,
    },
    shipment: {
      scope: "domestic",
      status: "not_shipped",
      method: "Premium Delivery",
      courier: "TCS",
      trackingNumber: null,
      estimatedDelivery: "2026-07-18T00:00:00Z",
      address: "House 24, DHA Phase 5, Lahore, Pakistan",
    },
    measurements: M({
      chest: 42,
      waist: 36,
      shoulder: 18.5,
      sleeve: 25.5,
      neck: 16.5,
      height: 71,
      notes: "Prefers a slightly tapered waist. Extra length on sleeves.",
      referenceImages: ["maroon", "charcoal"],
    }),
    assignedTailor: "Master Yousuf",
    eventDate: "2026-07-22T00:00:00Z",
    deliveryDeadline: "2026-07-18T00:00:00Z",
    customerNote: "Wedding is on the 22nd — need it a few days early for the fitting.",
    internalNote: "Groom order. Double-check embroidery alignment on the collar.",
    timeline: timelineFor("tailoring", "2026-07-04T08:10:00Z"),
    activity: [
      { id: "a1", actor: "Master Yousuf", action: "started tailoring", at: "2026-07-06T09:20:00Z" },
      { id: "a2", actor: "Sana (Ops)", action: "approved measurements", at: "2026-07-05T14:00:00Z" },
      { id: "a3", actor: "System", action: "payment confirmed", at: "2026-07-04T08:30:00Z" },
    ],
    createdAt: "2026-07-04T08:10:00Z",
    updatedAt: "2026-07-06T09:20:00Z",
  },
  {
    id: "ord_02",
    reference: "TMK-10481",
    type: "ready_to_wear",
    stage: "confirmed",
    priority: "standard",
    customer: {
      id: "cus_02",
      name: "Bilal Khan",
      initials: "BK",
      email: "bilal.khan@outlook.com",
      phone: "+92 301 2345678",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Karachi",
      addressLine: "Flat 7B, Clifton Block 4, Karachi",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 61000,
    },
    items: [
      {
        id: "li_02",
        name: "Charcoal Wool Waistcoat",
        image: "charcoal",
        type: "ready_to_wear",
        fabric: "Wool Blend",
        color: "Charcoal",
        size: "L",
        quantity: 1,
        unitPrice: 8900,
      },
      {
        id: "li_03",
        name: "Navy Formal Kurta",
        image: "navy",
        type: "ready_to_wear",
        fabric: "Egyptian Cotton",
        color: "Navy",
        size: "L",
        quantity: 1,
        unitPrice: 10000,
      },
    ],
    itemCount: 2,
    total: 18900,
    payment: {
      method: "Credit Card",
      status: "paid",
      transactionId: "TXN-77B120",
      subtotal: 18900,
      shipping: 350,
      discount: 350,
      tax: 0,
      total: 18900,
      paid: 18900,
    },
    shipment: {
      scope: "domestic",
      status: "processing",
      method: "Standard Delivery",
      courier: "Leopards",
      trackingNumber: null,
      estimatedDelivery: "2026-07-09T00:00:00Z",
      address: "Flat 7B, Clifton Block 4, Karachi, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-09T00:00:00Z",
    customerNote: null,
    internalNote: null,
    timeline: timelineFor("confirmed", "2026-07-04T06:40:00Z"),
    activity: [
      { id: "a1", actor: "System", action: "order confirmed", at: "2026-07-04T06:55:00Z" },
      { id: "a2", actor: "System", action: "payment confirmed", at: "2026-07-04T06:45:00Z" },
    ],
    createdAt: "2026-07-04T06:40:00Z",
    updatedAt: "2026-07-04T06:55:00Z",
  },
  {
    id: "ord_03",
    reference: "TMK-10480",
    type: "made_to_measure",
    stage: "pending",
    priority: "high",
    customer: {
      id: "cus_03",
      name: "Hamza Sheikh",
      initials: "HS",
      email: "h.sheikh@gmail.com",
      phone: "+92 302 3456789",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Islamabad",
      addressLine: "House 88, F-7/3, Islamabad",
      vip: false,
      ordersCount: 1,
      lifetimeValue: 52000,
    },
    items: [
      {
        id: "li_04",
        name: "Midnight Prince Coat",
        image: "black",
        type: "made_to_measure",
        fabric: "Velvet",
        color: "Black",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 52000,
      },
    ],
    itemCount: 1,
    total: 52000,
    payment: {
      method: "Bank Transfer",
      status: "unpaid",
      transactionId: "—",
      subtotal: 52000,
      shipping: 0,
      discount: 0,
      tax: 0,
      total: 52000,
      paid: 0,
    },
    shipment: {
      scope: "domestic",
      status: "not_shipped",
      method: "Premium Delivery",
      courier: "TCS",
      trackingNumber: null,
      estimatedDelivery: null,
      address: "House 88, F-7/3, Islamabad, Pakistan",
    },
    measurements: M({ chest: 44, waist: 38, height: 73, notes: "Awaiting confirmed measurements from studio visit." }),
    assignedTailor: null,
    eventDate: "2026-08-02T00:00:00Z",
    deliveryDeadline: "2026-07-28T00:00:00Z",
    customerNote: "Please call before confirming — want to discuss lapel style.",
    internalNote: "Payment pending. Hold production until 50% advance received.",
    timeline: timelineFor("pending", "2026-07-03T15:20:00Z"),
    activity: [
      { id: "a1", actor: "System", action: "order placed", at: "2026-07-03T15:20:00Z" },
    ],
    createdAt: "2026-07-03T15:20:00Z",
    updatedAt: "2026-07-03T15:20:00Z",
  },
  {
    id: "ord_04",
    reference: "TMK-10479",
    type: "ready_to_wear",
    stage: "shipped",
    priority: "standard",
    customer: {
      id: "cus_04",
      name: "Omar Farooq",
      initials: "OF",
      email: "omar.farooq@gmail.com",
      phone: "+971 50 4567890",
      country: "UAE",
      flag: "🇦🇪",
      city: "Dubai",
      addressLine: "Villa 12, Jumeirah 1, Dubai",
      vip: true,
      ordersCount: 5,
      lifetimeValue: 214000,
    },
    items: [
      {
        id: "li_05",
        name: "Sand Linen Shalwar Kameez",
        image: "sand",
        type: "ready_to_wear",
        fabric: "Linen",
        color: "Sand",
        size: "M",
        quantity: 1,
        unitPrice: 15600,
      },
    ],
    itemCount: 1,
    total: 15600,
    payment: {
      method: "Credit Card",
      status: "paid",
      transactionId: "TXN-4410CD",
      subtotal: 15600,
      shipping: 4200,
      discount: 0,
      tax: 0,
      total: 19800,
      paid: 19800,
    },
    shipment: {
      scope: "international",
      status: "in_transit",
      method: "International Express",
      courier: "DHL Express",
      trackingNumber: "DHL 8842019375",
      estimatedDelivery: "2026-07-10T00:00:00Z",
      address: "Villa 12, Jumeirah 1, Dubai, UAE",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-10T00:00:00Z",
    customerNote: null,
    internalNote: "Repeat international customer — priority handling on returns.",
    timeline: timelineFor("shipped", "2026-07-03T11:05:00Z"),
    activity: [
      { id: "a1", actor: "System", action: "handed to DHL Express", at: "2026-07-06T10:00:00Z" },
      { id: "a2", actor: "Warehouse", action: "packed & labelled", at: "2026-07-05T16:30:00Z" },
    ],
    createdAt: "2026-07-03T11:05:00Z",
    updatedAt: "2026-07-06T10:00:00Z",
  },
  {
    id: "ord_05",
    reference: "TMK-10478",
    type: "ready_to_wear",
    stage: "delivered",
    priority: "standard",
    customer: {
      id: "cus_05",
      name: "Fahad Malik",
      initials: "FM",
      email: "fahad.malik@gmail.com",
      phone: "+92 304 5678901",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Faisalabad",
      addressLine: "House 3, Madina Town, Faisalabad",
      vip: false,
      ordersCount: 4,
      lifetimeValue: 98000,
    },
    items: [
      {
        id: "li_06",
        name: "Emerald Silk Kurta",
        image: "emerald",
        type: "ready_to_wear",
        fabric: "Raw Silk",
        color: "Emerald",
        size: "M",
        quantity: 2,
        unitPrice: 10400,
      },
      {
        id: "li_07",
        name: "Ivory Cotton Shalwar",
        image: "ivory",
        type: "ready_to_wear",
        fabric: "Egyptian Cotton",
        color: "Ivory",
        size: "M",
        quantity: 1,
        unitPrice: 10400,
      },
    ],
    itemCount: 3,
    total: 31200,
    payment: {
      method: "Cash on Delivery",
      status: "paid",
      transactionId: "COD-30219",
      subtotal: 31200,
      shipping: 300,
      discount: 300,
      tax: 0,
      total: 31200,
      paid: 31200,
    },
    shipment: {
      scope: "domestic",
      status: "delivered",
      method: "Standard Delivery",
      courier: "M&P",
      trackingNumber: "MP 552019",
      estimatedDelivery: "2026-07-04T00:00:00Z",
      address: "House 3, Madina Town, Faisalabad, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-04T00:00:00Z",
    customerNote: null,
    internalNote: null,
    timeline: timelineFor("delivered", "2026-07-02T18:45:00Z"),
    activity: [
      { id: "a1", actor: "M&P", action: "delivered to customer", at: "2026-07-05T13:10:00Z" },
      { id: "a2", actor: "System", action: "out for delivery", at: "2026-07-05T08:00:00Z" },
    ],
    createdAt: "2026-07-02T18:45:00Z",
    updatedAt: "2026-07-05T13:10:00Z",
  },
  {
    id: "ord_06",
    reference: "TMK-10477",
    type: "ready_to_wear",
    stage: "cancelled",
    priority: "standard",
    customer: {
      id: "cus_06",
      name: "Zeeshan Ali",
      initials: "ZA",
      email: "zeeshan.ali@gmail.com",
      phone: "+92 305 6789012",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Multan",
      addressLine: "House 41, Cantt, Multan",
      vip: false,
      ordersCount: 1,
      lifetimeValue: 9800,
    },
    items: [
      {
        id: "li_08",
        name: "Maroon Velvet Waistcoat",
        image: "maroon",
        type: "ready_to_wear",
        fabric: "Velvet",
        color: "Maroon",
        size: "S",
        quantity: 1,
        unitPrice: 9800,
      },
    ],
    itemCount: 1,
    total: 9800,
    payment: {
      method: "Credit Card",
      status: "refunded",
      transactionId: "TXN-1102FF",
      subtotal: 9800,
      shipping: 0,
      discount: 0,
      tax: 0,
      total: 9800,
      paid: 0,
    },
    shipment: {
      scope: "domestic",
      status: "not_shipped",
      method: "Standard Delivery",
      courier: "Leopards",
      trackingNumber: null,
      estimatedDelivery: null,
      address: "House 41, Cantt, Multan, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: null,
    customerNote: "Ordered the wrong size, please cancel.",
    internalNote: "Cancelled within 2h — full refund issued, no restocking fee.",
    timeline: buildTimeline("2026-07-02T10:15:00Z", 2),
    activity: [
      { id: "a1", actor: "Sana (Ops)", action: "issued full refund", at: "2026-07-02T12:40:00Z" },
      { id: "a2", actor: "Zeeshan Ali", action: "requested cancellation", at: "2026-07-02T12:20:00Z" },
    ],
    createdAt: "2026-07-02T10:15:00Z",
    updatedAt: "2026-07-02T12:40:00Z",
  },
  {
    id: "ord_07",
    reference: "TMK-10476",
    type: "custom_tailoring",
    stage: "ready",
    priority: "high",
    customer: {
      id: "cus_07",
      name: "Imran Yousaf",
      initials: "IY",
      email: "imran.y@gmail.com",
      phone: "+44 7700 900123",
      country: "United Kingdom",
      flag: "🇬🇧",
      city: "London",
      addressLine: "42 Baker Street, London",
      vip: true,
      ordersCount: 9,
      lifetimeValue: 612000,
    },
    items: [
      {
        id: "li_09",
        name: "Navy Three-Piece Bespoke Suit",
        image: "navy",
        type: "custom_tailoring",
        fabric: "Wool Blend",
        color: "Navy",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 46500,
      },
    ],
    itemCount: 1,
    total: 46500,
    payment: {
      method: "Bank Transfer",
      status: "paid",
      transactionId: "TXN-5590AA",
      subtotal: 46500,
      shipping: 6500,
      discount: 0,
      tax: 0,
      total: 53000,
      paid: 53000,
    },
    shipment: {
      scope: "international",
      status: "not_shipped",
      method: "International Express",
      courier: "FedEx",
      trackingNumber: null,
      estimatedDelivery: "2026-07-14T00:00:00Z",
      address: "42 Baker Street, London, United Kingdom",
    },
    measurements: M({
      chest: 41,
      waist: 35,
      shoulder: 18,
      sleeve: 26,
      neck: 16,
      inseam: 33,
      height: 72,
      notes: "Working cuffs on jacket. Trouser break: slight.",
      referenceImages: ["navy"],
    }),
    assignedTailor: "Master Iqbal",
    eventDate: "2026-07-20T00:00:00Z",
    deliveryDeadline: "2026-07-14T00:00:00Z",
    customerNote: "Ninth order — you know my fit. Trust your judgement on the finish.",
    internalNote: "VIP. Final press done, awaiting QC sign-off before international dispatch.",
    timeline: timelineFor("ready", "2026-07-01T14:30:00Z"),
    activity: [
      { id: "a1", actor: "Master Iqbal", action: "marked ready for QC", at: "2026-07-06T11:00:00Z" },
      { id: "a2", actor: "Master Iqbal", action: "completed tailoring", at: "2026-07-05T17:00:00Z" },
    ],
    createdAt: "2026-07-01T14:30:00Z",
    updatedAt: "2026-07-06T11:00:00Z",
  },
  {
    id: "ord_08",
    reference: "TMK-10475",
    type: "ready_to_wear",
    stage: "delivered",
    priority: "standard",
    customer: {
      id: "cus_08",
      name: "Saad Iqbal",
      initials: "SI",
      email: "saad.iqbal@gmail.com",
      phone: "+92 307 8901234",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Rawalpindi",
      addressLine: "House 9, Bahria Town, Rawalpindi",
      vip: false,
      ordersCount: 3,
      lifetimeValue: 74000,
    },
    items: [
      {
        id: "li_10",
        name: "Charcoal Formal Kurta",
        image: "charcoal",
        type: "ready_to_wear",
        fabric: "Wool Blend",
        color: "Charcoal",
        size: "L",
        quantity: 2,
        unitPrice: 11200,
      },
    ],
    itemCount: 2,
    total: 22400,
    payment: {
      method: "Credit Card",
      status: "paid",
      transactionId: "TXN-8830BC",
      subtotal: 22400,
      shipping: 300,
      discount: 300,
      tax: 0,
      total: 22400,
      paid: 22400,
    },
    shipment: {
      scope: "domestic",
      status: "delivered",
      method: "Standard Delivery",
      courier: "TCS",
      trackingNumber: "TCS 771230",
      estimatedDelivery: "2026-07-03T00:00:00Z",
      address: "House 9, Bahria Town, Rawalpindi, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-03T00:00:00Z",
    customerNote: null,
    internalNote: null,
    timeline: timelineFor("delivered", "2026-07-01T09:00:00Z"),
    activity: [
      { id: "a1", actor: "TCS", action: "delivered to customer", at: "2026-07-03T15:20:00Z" },
    ],
    createdAt: "2026-07-01T09:00:00Z",
    updatedAt: "2026-07-03T15:20:00Z",
  },
  {
    id: "ord_09",
    reference: "TMK-10474",
    type: "made_to_measure",
    stage: "measurements",
    priority: "high",
    customer: {
      id: "cus_09",
      name: "Abdullah Al-Rashid",
      initials: "AA",
      email: "a.alrashid@gmail.com",
      phone: "+966 55 1234567",
      country: "Saudi Arabia",
      flag: "🇸🇦",
      city: "Riyadh",
      addressLine: "King Fahd Rd, Al Olaya, Riyadh",
      vip: true,
      ordersCount: 6,
      lifetimeValue: 331000,
    },
    items: [
      {
        id: "li_11",
        name: "Ivory Wedding Sherwani",
        image: "ivory",
        type: "made_to_measure",
        fabric: "Jamawar",
        color: "Ivory",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 68000,
      },
    ],
    itemCount: 1,
    total: 68000,
    payment: {
      method: "Bank Transfer",
      status: "partially_paid",
      transactionId: "TXN-6621DE",
      subtotal: 68000,
      shipping: 8000,
      discount: 0,
      tax: 0,
      total: 76000,
      paid: 38000,
    },
    shipment: {
      scope: "international",
      status: "not_shipped",
      method: "International Express",
      courier: "DHL Express",
      trackingNumber: null,
      estimatedDelivery: "2026-07-26T00:00:00Z",
      address: "King Fahd Rd, Al Olaya, Riyadh, Saudi Arabia",
    },
    measurements: M({
      chest: 43,
      waist: 37,
      shoulder: 19,
      sleeve: 26,
      neck: 17,
      height: 74,
      notes: "High collar preference. Gold thread accent on cuffs.",
      referenceImages: ["ivory", "sand"],
    }),
    assignedTailor: "Master Rehman",
    eventDate: "2026-07-30T00:00:00Z",
    deliveryDeadline: "2026-07-26T00:00:00Z",
    customerNote: "This is for my wedding — everything must be perfect.",
    internalNote: "50% advance received. Confirm measurements before cutting Jamawar.",
    timeline: timelineFor("measurements", "2026-07-05T10:00:00Z"),
    activity: [
      { id: "a1", actor: "Master Rehman", action: "received measurements", at: "2026-07-06T09:00:00Z" },
      { id: "a2", actor: "System", action: "advance payment received", at: "2026-07-05T11:00:00Z" },
    ],
    createdAt: "2026-07-05T10:00:00Z",
    updatedAt: "2026-07-06T09:00:00Z",
  },
  {
    id: "ord_10",
    reference: "TMK-10473",
    type: "custom_tailoring",
    stage: "fabric",
    priority: "urgent",
    customer: {
      id: "cus_10",
      name: "Daniyal Ahmed",
      initials: "DA",
      email: "daniyal.ahmed@gmail.com",
      phone: "+92 308 9012345",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Lahore",
      addressLine: "House 15, Gulberg III, Lahore",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 89000,
    },
    items: [
      {
        id: "li_12",
        name: "Black Velvet Prince Coat",
        image: "black",
        type: "custom_tailoring",
        fabric: "Velvet",
        color: "Black",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 58000,
      },
    ],
    itemCount: 1,
    total: 58000,
    payment: {
      method: "Bank Transfer",
      status: "paid",
      transactionId: "TXN-2240EF",
      subtotal: 58000,
      shipping: 0,
      discount: 2000,
      tax: 0,
      total: 56000,
      paid: 56000,
    },
    shipment: {
      scope: "domestic",
      status: "not_shipped",
      method: "Premium Delivery",
      courier: "TCS",
      trackingNumber: null,
      estimatedDelivery: "2026-07-16T00:00:00Z",
      address: "House 15, Gulberg III, Lahore, Pakistan",
    },
    measurements: M({
      chest: 40,
      waist: 33,
      shoulder: 17.5,
      sleeve: 25,
      height: 69,
      notes: "Slim fit throughout. Peak lapel.",
      referenceImages: ["black"],
    }),
    assignedTailor: "Master Nadeem",
    eventDate: "2026-07-19T00:00:00Z",
    deliveryDeadline: "2026-07-16T00:00:00Z",
    customerNote: "Need this urgently for an engagement.",
    internalNote: "Fabric being sourced — velvet stock confirmed with supplier.",
    timeline: timelineFor("fabric", "2026-07-05T13:00:00Z"),
    activity: [
      { id: "a1", actor: "Master Nadeem", action: "selecting fabric", at: "2026-07-06T14:00:00Z" },
      { id: "a2", actor: "Sana (Ops)", action: "approved measurements", at: "2026-07-06T10:00:00Z" },
    ],
    createdAt: "2026-07-05T13:00:00Z",
    updatedAt: "2026-07-06T14:00:00Z",
  },
  {
    id: "ord_11",
    reference: "TMK-10472",
    type: "custom_tailoring",
    stage: "quality_check",
    priority: "high",
    customer: {
      id: "cus_11",
      name: "Kamran Shah",
      initials: "KS",
      email: "kamran.shah@gmail.com",
      phone: "+1 416 555 0192",
      country: "Canada",
      flag: "🇨🇦",
      city: "Toronto",
      addressLine: "88 Yonge Street, Toronto",
      vip: false,
      ordersCount: 3,
      lifetimeValue: 176000,
    },
    items: [
      {
        id: "li_13",
        name: "Charcoal Bespoke Two-Piece",
        image: "charcoal",
        type: "custom_tailoring",
        fabric: "Wool Blend",
        color: "Charcoal",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 44000,
      },
    ],
    itemCount: 1,
    total: 44000,
    payment: {
      method: "Credit Card",
      status: "paid",
      transactionId: "TXN-9931GH",
      subtotal: 44000,
      shipping: 7000,
      discount: 0,
      tax: 0,
      total: 51000,
      paid: 51000,
    },
    shipment: {
      scope: "international",
      status: "not_shipped",
      method: "International Express",
      courier: "FedEx",
      trackingNumber: null,
      estimatedDelivery: "2026-07-15T00:00:00Z",
      address: "88 Yonge Street, Toronto, Canada",
    },
    measurements: M({
      chest: 42,
      waist: 36,
      shoulder: 18.5,
      sleeve: 25.5,
      inseam: 32,
      height: 71,
      notes: "Half-canvas construction. Functional boutonnière loop.",
      referenceImages: ["charcoal"],
    }),
    assignedTailor: "Master Iqbal",
    eventDate: null,
    deliveryDeadline: "2026-07-15T00:00:00Z",
    customerNote: null,
    internalNote: "In QC — checking button stance and pick stitching.",
    timeline: timelineFor("quality_check", "2026-07-02T09:00:00Z"),
    activity: [
      { id: "a1", actor: "QC Team", action: "started quality check", at: "2026-07-06T15:00:00Z" },
      { id: "a2", actor: "Master Iqbal", action: "completed tailoring", at: "2026-07-06T09:00:00Z" },
    ],
    createdAt: "2026-07-02T09:00:00Z",
    updatedAt: "2026-07-06T15:00:00Z",
  },
  {
    id: "ord_12",
    reference: "TMK-10471",
    type: "ready_to_wear",
    stage: "packed",
    priority: "standard",
    customer: {
      id: "cus_12",
      name: "Tariq Mehmood",
      initials: "TM",
      email: "tariq.m@gmail.com",
      phone: "+92 309 0123456",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Peshawar",
      addressLine: "House 6, University Town, Peshawar",
      vip: false,
      ordersCount: 5,
      lifetimeValue: 121000,
    },
    items: [
      {
        id: "li_14",
        name: "Sand Cotton Kurta Set",
        image: "sand",
        type: "ready_to_wear",
        fabric: "Egyptian Cotton",
        color: "Sand",
        size: "XL",
        quantity: 2,
        unitPrice: 13500,
      },
    ],
    itemCount: 2,
    total: 27000,
    payment: {
      method: "Cash on Delivery",
      status: "unpaid",
      transactionId: "COD-40188",
      subtotal: 27000,
      shipping: 300,
      discount: 0,
      tax: 0,
      total: 27300,
      paid: 0,
    },
    shipment: {
      scope: "domestic",
      status: "processing",
      method: "Standard Delivery",
      courier: "Leopards",
      trackingNumber: null,
      estimatedDelivery: "2026-07-09T00:00:00Z",
      address: "House 6, University Town, Peshawar, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-09T00:00:00Z",
    customerNote: null,
    internalNote: "COD — confirm availability by phone before dispatch.",
    timeline: timelineFor("packed", "2026-07-04T12:00:00Z"),
    activity: [
      { id: "a1", actor: "Warehouse", action: "packed order", at: "2026-07-06T16:00:00Z" },
    ],
    createdAt: "2026-07-04T12:00:00Z",
    updatedAt: "2026-07-06T16:00:00Z",
  },
  {
    id: "ord_13",
    reference: "TMK-10470",
    type: "made_to_measure",
    stage: "refund_requested",
    priority: "standard",
    customer: {
      id: "cus_13",
      name: "Junaid Akbar",
      initials: "JA",
      email: "junaid.akbar@gmail.com",
      phone: "+92 310 1234567",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Sialkot",
      addressLine: "House 2, Cantt, Sialkot",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 64000,
    },
    items: [
      {
        id: "li_15",
        name: "Navy Made-to-Measure Waistcoat",
        image: "navy",
        type: "made_to_measure",
        fabric: "Wool Blend",
        color: "Navy",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 24000,
      },
    ],
    itemCount: 1,
    total: 24000,
    payment: {
      method: "Credit Card",
      status: "refund_requested",
      transactionId: "TXN-1177IJ",
      subtotal: 24000,
      shipping: 300,
      discount: 0,
      tax: 0,
      total: 24300,
      paid: 24300,
    },
    shipment: {
      scope: "domestic",
      status: "delivered",
      method: "Standard Delivery",
      courier: "TCS",
      trackingNumber: "TCS 883012",
      estimatedDelivery: "2026-07-01T00:00:00Z",
      address: "House 2, Cantt, Sialkot, Pakistan",
    },
    measurements: M({ chest: 39, waist: 34, height: 68 }),
    assignedTailor: "Master Rehman",
    eventDate: null,
    deliveryDeadline: "2026-07-01T00:00:00Z",
    customerNote: "The fit around the chest is loose — requesting a refund or alteration.",
    internalNote: "Refund under review. Offer free alteration first before approving.",
    timeline: buildTimeline("2026-06-26T10:00:00Z", 10),
    activity: [
      { id: "a1", actor: "Junaid Akbar", action: "requested a refund", at: "2026-07-05T18:00:00Z" },
      { id: "a2", actor: "TCS", action: "delivered to customer", at: "2026-07-01T14:00:00Z" },
    ],
    createdAt: "2026-06-26T10:00:00Z",
    updatedAt: "2026-07-05T18:00:00Z",
  },
  {
    id: "ord_14",
    reference: "TMK-10469",
    type: "ready_to_wear",
    stage: "confirmed",
    priority: "standard",
    customer: {
      id: "cus_14",
      name: "Michael Chen",
      initials: "MC",
      email: "m.chen@gmail.com",
      phone: "+1 415 555 0147",
      country: "United States",
      flag: "🇺🇸",
      city: "San Francisco",
      addressLine: "500 Market St, San Francisco",
      vip: false,
      ordersCount: 1,
      lifetimeValue: 34000,
    },
    items: [
      {
        id: "li_16",
        name: "Emerald Silk Sherwani",
        image: "emerald",
        type: "ready_to_wear",
        fabric: "Raw Silk",
        color: "Emerald",
        size: "M",
        quantity: 1,
        unitPrice: 34000,
      },
    ],
    itemCount: 1,
    total: 34000,
    payment: {
      method: "Credit Card",
      status: "paid",
      transactionId: "TXN-3390KL",
      subtotal: 34000,
      shipping: 7500,
      discount: 0,
      tax: 0,
      total: 41500,
      paid: 41500,
    },
    shipment: {
      scope: "international",
      status: "processing",
      method: "International Express",
      courier: "FedEx",
      trackingNumber: null,
      estimatedDelivery: "2026-07-13T00:00:00Z",
      address: "500 Market St, San Francisco, United States",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-13T00:00:00Z",
    customerNote: "First time ordering — attending a friend's wedding.",
    internalNote: null,
    timeline: timelineFor("confirmed", "2026-07-05T20:00:00Z"),
    activity: [
      { id: "a1", actor: "System", action: "order confirmed", at: "2026-07-05T20:10:00Z" },
    ],
    createdAt: "2026-07-05T20:00:00Z",
    updatedAt: "2026-07-05T20:10:00Z",
  },
  {
    id: "ord_15",
    reference: "TMK-10468",
    type: "custom_tailoring",
    stage: "delivered",
    priority: "standard",
    customer: {
      id: "cus_15",
      name: "Yousaf Nawaz",
      initials: "YN",
      email: "yousaf.n@gmail.com",
      phone: "+974 5512 3456",
      country: "Qatar",
      flag: "🇶🇦",
      city: "Doha",
      addressLine: "West Bay, Doha",
      vip: true,
      ordersCount: 8,
      lifetimeValue: 540000,
    },
    items: [
      {
        id: "li_17",
        name: "Maroon Bespoke Sherwani",
        image: "maroon",
        type: "custom_tailoring",
        fabric: "Jamawar",
        color: "Maroon",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 72000,
      },
    ],
    itemCount: 1,
    total: 72000,
    payment: {
      method: "Bank Transfer",
      status: "paid",
      transactionId: "TXN-7712MN",
      subtotal: 72000,
      shipping: 8500,
      discount: 5000,
      tax: 0,
      total: 75500,
      paid: 75500,
    },
    shipment: {
      scope: "international",
      status: "delivered",
      method: "International Express",
      courier: "DHL Express",
      trackingNumber: "DHL 9920184756",
      estimatedDelivery: "2026-07-02T00:00:00Z",
      address: "West Bay, Doha, Qatar",
    },
    measurements: M({
      chest: 44,
      waist: 39,
      shoulder: 19.5,
      sleeve: 26.5,
      neck: 17.5,
      height: 75,
      notes: "Loyal VIP. Standard bespoke block on file.",
      referenceImages: ["maroon"],
    }),
    assignedTailor: "Master Yousuf",
    eventDate: "2026-07-05T00:00:00Z",
    deliveryDeadline: "2026-07-02T00:00:00Z",
    customerNote: "As always, impeccable work expected.",
    internalNote: "VIP delivered ahead of schedule. Send thank-you note.",
    timeline: timelineFor("delivered", "2026-06-20T09:00:00Z"),
    activity: [
      { id: "a1", actor: "DHL Express", action: "delivered to customer", at: "2026-07-01T12:00:00Z" },
      { id: "a2", actor: "QC Team", action: "passed final quality check", at: "2026-06-28T15:00:00Z" },
    ],
    createdAt: "2026-06-20T09:00:00Z",
    updatedAt: "2026-07-01T12:00:00Z",
  },
  {
    id: "ord_16",
    reference: "TMK-10467",
    type: "ready_to_wear",
    stage: "pending",
    priority: "standard",
    customer: {
      id: "cus_16",
      name: "Waleed Hassan",
      initials: "WH",
      email: "waleed.hassan@gmail.com",
      phone: "+92 311 2345678",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Hyderabad",
      addressLine: "House 12, Latifabad, Hyderabad",
      vip: false,
      ordersCount: 1,
      lifetimeValue: 12500,
    },
    items: [
      {
        id: "li_18",
        name: "Navy Cotton Kurta",
        image: "navy",
        type: "ready_to_wear",
        fabric: "Egyptian Cotton",
        color: "Navy",
        size: "M",
        quantity: 1,
        unitPrice: 12500,
      },
    ],
    itemCount: 1,
    total: 12500,
    payment: {
      method: "Cash on Delivery",
      status: "unpaid",
      transactionId: "COD-40901",
      subtotal: 12500,
      shipping: 300,
      discount: 0,
      tax: 0,
      total: 12800,
      paid: 0,
    },
    shipment: {
      scope: "domestic",
      status: "not_shipped",
      method: "Standard Delivery",
      courier: "M&P",
      trackingNumber: null,
      estimatedDelivery: null,
      address: "House 12, Latifabad, Hyderabad, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: "2026-07-11T00:00:00Z",
    customerNote: null,
    internalNote: null,
    timeline: timelineFor("pending", "2026-07-06T07:30:00Z"),
    activity: [
      { id: "a1", actor: "System", action: "order placed", at: "2026-07-06T07:30:00Z" },
    ],
    createdAt: "2026-07-06T07:30:00Z",
    updatedAt: "2026-07-06T07:30:00Z",
  },
  {
    id: "ord_17",
    reference: "TMK-10466",
    type: "made_to_measure",
    stage: "tailoring",
    priority: "high",
    customer: {
      id: "cus_17",
      name: "Ali Raza Bukhari",
      initials: "AB",
      email: "ali.bukhari@gmail.com",
      phone: "+61 4 1234 5678",
      country: "Australia",
      flag: "🇦🇺",
      city: "Sydney",
      addressLine: "17 George St, Sydney",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 92000,
    },
    items: [
      {
        id: "li_19",
        name: "Charcoal MTM Three-Piece",
        image: "charcoal",
        type: "made_to_measure",
        fabric: "Wool Blend",
        color: "Charcoal",
        size: "Bespoke",
        quantity: 1,
        unitPrice: 47000,
      },
    ],
    itemCount: 1,
    total: 47000,
    payment: {
      method: "Credit Card",
      status: "paid",
      transactionId: "TXN-4408OP",
      subtotal: 47000,
      shipping: 9000,
      discount: 0,
      tax: 0,
      total: 56000,
      paid: 56000,
    },
    shipment: {
      scope: "international",
      status: "not_shipped",
      method: "International Express",
      courier: "FedEx",
      trackingNumber: null,
      estimatedDelivery: "2026-07-21T00:00:00Z",
      address: "17 George St, Sydney, Australia",
    },
    measurements: M({
      chest: 41,
      waist: 35,
      shoulder: 18,
      sleeve: 25.5,
      inseam: 33,
      height: 72,
      notes: "Ticket pocket on jacket. Side adjusters on trousers.",
      referenceImages: ["charcoal", "navy"],
    }),
    assignedTailor: "Master Nadeem",
    eventDate: "2026-07-25T00:00:00Z",
    deliveryDeadline: "2026-07-21T00:00:00Z",
    customerNote: null,
    internalNote: "In tailoring — jacket basted, first fitting photos sent.",
    timeline: timelineFor("tailoring", "2026-07-01T08:00:00Z"),
    activity: [
      { id: "a1", actor: "Master Nadeem", action: "started tailoring", at: "2026-07-06T09:00:00Z" },
    ],
    createdAt: "2026-07-01T08:00:00Z",
    updatedAt: "2026-07-06T09:00:00Z",
  },
  {
    id: "ord_18",
    reference: "TMK-10465",
    type: "ready_to_wear",
    stage: "refunded",
    priority: "standard",
    customer: {
      id: "cus_18",
      name: "Noman Siddiqui",
      initials: "NS",
      email: "noman.s@gmail.com",
      phone: "+92 312 3456789",
      country: "Pakistan",
      flag: "🇵🇰",
      city: "Quetta",
      addressLine: "House 5, Jinnah Road, Quetta",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 21000,
    },
    items: [
      {
        id: "li_20",
        name: "Black Formal Waistcoat",
        image: "black",
        type: "ready_to_wear",
        fabric: "Wool Blend",
        color: "Black",
        size: "L",
        quantity: 1,
        unitPrice: 21000,
      },
    ],
    itemCount: 1,
    total: 21000,
    payment: {
      method: "Credit Card",
      status: "refunded",
      transactionId: "TXN-5519QR",
      subtotal: 21000,
      shipping: 300,
      discount: 0,
      tax: 0,
      total: 21300,
      paid: 0,
    },
    shipment: {
      scope: "domestic",
      status: "returned",
      method: "Standard Delivery",
      courier: "Leopards",
      trackingNumber: "LEO 220194",
      estimatedDelivery: "2026-06-28T00:00:00Z",
      address: "House 5, Jinnah Road, Quetta, Pakistan",
    },
    measurements: null,
    assignedTailor: null,
    eventDate: null,
    deliveryDeadline: null,
    customerNote: "Item didn't match the photos, returned it.",
    internalNote: "Returned & refunded. Flag product listing photos for review.",
    timeline: buildTimeline("2026-06-24T10:00:00Z", 10),
    activity: [
      { id: "a1", actor: "Sana (Ops)", action: "completed refund", at: "2026-07-03T11:00:00Z" },
      { id: "a2", actor: "Warehouse", action: "received return", at: "2026-07-02T10:00:00Z" },
    ],
    createdAt: "2026-06-24T10:00:00Z",
    updatedAt: "2026-07-03T11:00:00Z",
  },
]
