import type { Product } from "@/types"

function variants(
  sizes: string[],
  colors: string[],
  perVariant: number
): Product["variants"] {
  const out: Product["variants"] = []
  sizes.forEach((size) =>
    colors.forEach((color) =>
      out.push({
        id: `${size}-${color}`.toLowerCase(),
        size,
        color,
        stock: perVariant,
      })
    )
  )
  return out
}

export const products: Product[] = [
  {
    id: "prd_01",
    name: "Maroon Velvet Sherwani",
    slug: "maroon-velvet-sherwani",
    sku: "SHW-MRN-42",
    image: "maroon",
    category: "Sherwanis",
    collection: "Wedding Collection",
    price: 48500,
    salePrice: 42000,
    costPrice: 24000,
    stock: 2,
    lowStockThreshold: 10,
    status: "active",
    featured: true,
    fabric: "Velvet",
    sizes: ["M", "L", "XL"],
    colors: ["Maroon"],
    variants: variants(["M", "L", "XL"], ["Maroon"], 1),
    shortDescription:
      "Hand-embroidered velvet sherwani with antique gold threadwork.",
    createdAt: "2026-05-14T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "prd_02",
    name: "Ivory Silk Prince Coat",
    slug: "ivory-silk-prince-coat",
    sku: "PRC-IVR-40",
    image: "ivory",
    category: "Prince Coats",
    collection: "Wedding Collection",
    price: 39000,
    costPrice: 19500,
    stock: 18,
    lowStockThreshold: 10,
    status: "active",
    featured: true,
    fabric: "Raw Silk",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory"],
    variants: variants(["S", "M", "L", "XL"], ["Ivory"], 4),
    shortDescription: "Structured raw-silk prince coat with a satin shawl lapel.",
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-06-28T09:00:00Z",
  },
  {
    id: "prd_03",
    name: "Charcoal Three-Piece Suit",
    slug: "charcoal-three-piece-suit",
    sku: "WST-CHR-40",
    image: "charcoal",
    category: "Western Suits",
    collection: "Best Sellers",
    price: 34500,
    salePrice: 29900,
    costPrice: 17000,
    stock: 26,
    lowStockThreshold: 12,
    status: "active",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal"],
    variants: variants(["S", "M", "L", "XL", "XXL"], ["Charcoal"], 5),
    shortDescription: "Slim-fit wool-blend three-piece with a peak lapel.",
    createdAt: "2026-04-02T09:00:00Z",
    updatedAt: "2026-06-30T09:00:00Z",
  },
  {
    id: "prd_04",
    name: "Navy Classic Waistcoat",
    slug: "navy-classic-waistcoat",
    sku: "WSC-NVY-38",
    image: "navy",
    category: "Waistcoats",
    collection: "Best Sellers",
    price: 12500,
    costPrice: 5200,
    stock: 4,
    lowStockThreshold: 15,
    status: "active",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy"],
    variants: variants(["S", "M", "L", "XL"], ["Navy"], 1),
    shortDescription: "Five-button waistcoat with adjustable satin back strap.",
    createdAt: "2026-03-11T09:00:00Z",
    updatedAt: "2026-06-25T09:00:00Z",
  },
  {
    id: "prd_05",
    name: "Emerald Jamawar Sherwani",
    slug: "emerald-jamawar-sherwani",
    sku: "SHW-EMR-44",
    image: "emerald",
    category: "Sherwanis",
    collection: "Eid Collection",
    price: 52000,
    costPrice: 26000,
    stock: 9,
    lowStockThreshold: 8,
    status: "active",
    featured: true,
    fabric: "Jamawar",
    sizes: ["M", "L", "XL"],
    colors: ["Emerald"],
    variants: variants(["M", "L", "XL"], ["Emerald"], 3),
    shortDescription: "Woven jamawar sherwani with a contrast churidar set.",
    createdAt: "2026-06-01T09:00:00Z",
    updatedAt: "2026-07-02T09:00:00Z",
  },
  {
    id: "prd_06",
    name: "Sand Linen Kurta",
    slug: "sand-linen-kurta",
    sku: "KRT-SND-40",
    image: "sand",
    category: "Kurtas",
    collection: "Summer Collection",
    price: 8900,
    salePrice: 6900,
    costPrice: 3200,
    stock: 41,
    lowStockThreshold: 20,
    status: "active",
    featured: false,
    fabric: "Linen",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand"],
    variants: variants(["S", "M", "L", "XL", "XXL"], ["Sand"], 8),
    shortDescription: "Breathable linen kurta with mother-of-pearl buttons.",
    createdAt: "2026-05-30T09:00:00Z",
    updatedAt: "2026-06-29T09:00:00Z",
  },
  {
    id: "prd_07",
    name: "Black Tuxedo Dinner Suit",
    slug: "black-tuxedo-dinner-suit",
    sku: "WST-BLK-42",
    image: "black",
    category: "Western Suits",
    collection: "New Arrivals",
    price: 44000,
    costPrice: 22000,
    stock: 0,
    lowStockThreshold: 10,
    status: "active",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["M", "L", "XL"],
    colors: ["Black"],
    variants: variants(["M", "L", "XL"], ["Black"], 0),
    shortDescription: "Satin-lapel tuxedo with matching bow tie and cummerbund.",
    createdAt: "2026-06-18T09:00:00Z",
    updatedAt: "2026-07-03T09:00:00Z",
  },
  {
    id: "prd_08",
    name: "Ivory Embroidered Shalwar Kameez",
    slug: "ivory-embroidered-shalwar-kameez",
    sku: "SLK-IVR-40",
    image: "ivory",
    category: "Shalwar Kameez",
    collection: "Eid Collection",
    price: 15500,
    costPrice: 7000,
    stock: 1,
    lowStockThreshold: 10,
    status: "active",
    featured: true,
    fabric: "Egyptian Cotton",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory"],
    variants: variants(["S", "M", "L", "XL"], ["Ivory"], 1),
    shortDescription: "Cotton shalwar kameez with tone-on-tone chest embroidery.",
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "prd_09",
    name: "Slate Peak-Lapel Waistcoat",
    slug: "slate-peak-lapel-waistcoat",
    sku: "WSC-SLT-40",
    image: "charcoal",
    category: "Waistcoats",
    collection: "New Arrivals",
    price: 13900,
    costPrice: 5800,
    stock: 22,
    lowStockThreshold: 12,
    status: "draft",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal"],
    variants: variants(["S", "M", "L", "XL"], ["Charcoal"], 5),
    shortDescription: "Double-breasted waistcoat with a satin peak lapel.",
    createdAt: "2026-06-22T09:00:00Z",
    updatedAt: "2026-07-02T09:00:00Z",
  },
  {
    id: "prd_10",
    name: "Navy Bandhgala Prince Coat",
    slug: "navy-bandhgala-prince-coat",
    sku: "PRC-NVY-42",
    image: "navy",
    category: "Prince Coats",
    collection: "Wedding Collection",
    price: 41500,
    costPrice: 20500,
    stock: 14,
    lowStockThreshold: 10,
    status: "active",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["M", "L", "XL"],
    colors: ["Navy"],
    variants: variants(["M", "L", "XL"], ["Navy"], 4),
    shortDescription: "Bandhgala prince coat with a mandarin collar and brooch.",
    createdAt: "2026-04-27T09:00:00Z",
    updatedAt: "2026-06-20T09:00:00Z",
  },
  {
    id: "prd_11",
    name: "Emerald Silk Kurta Set",
    slug: "emerald-silk-kurta-set",
    sku: "KRT-EMR-40",
    image: "emerald",
    category: "Kurtas",
    collection: "Eid Collection",
    price: 11900,
    costPrice: 5200,
    stock: 33,
    lowStockThreshold: 15,
    status: "active",
    featured: false,
    fabric: "Raw Silk",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Emerald"],
    variants: variants(["S", "M", "L", "XL"], ["Emerald"], 8),
    shortDescription: "Raw-silk kurta with a coordinated waistcoat.",
    createdAt: "2026-05-25T09:00:00Z",
    updatedAt: "2026-06-27T09:00:00Z",
  },
  {
    id: "prd_12",
    name: "Charcoal Herringbone Sherwani",
    slug: "charcoal-herringbone-sherwani",
    sku: "SHW-CHR-42",
    image: "charcoal",
    category: "Sherwanis",
    collection: "New Arrivals",
    price: 46500,
    costPrice: 23000,
    stock: 7,
    lowStockThreshold: 8,
    status: "active",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["M", "L", "XL"],
    colors: ["Charcoal"],
    variants: variants(["M", "L", "XL"], ["Charcoal"], 2),
    shortDescription: "Herringbone sherwani with self-tone buttons.",
    createdAt: "2026-06-10T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "prd_13",
    name: "Sand Cotton Waistcoat",
    slug: "sand-cotton-waistcoat",
    sku: "WSC-SND-38",
    image: "sand",
    category: "Waistcoats",
    collection: "Summer Collection",
    price: 9900,
    costPrice: 4100,
    stock: 0,
    lowStockThreshold: 12,
    status: "archived",
    featured: false,
    fabric: "Egyptian Cotton",
    sizes: ["S", "M", "L"],
    colors: ["Sand"],
    variants: variants(["S", "M", "L"], ["Sand"], 0),
    shortDescription: "Lightweight cotton waistcoat for warm-weather events.",
    createdAt: "2026-02-15T09:00:00Z",
    updatedAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "prd_14",
    name: "Black Slim Western Suit",
    slug: "black-slim-western-suit",
    sku: "WST-BLK-38",
    image: "black",
    category: "Western Suits",
    collection: "Best Sellers",
    price: 32000,
    salePrice: 27500,
    costPrice: 15500,
    stock: 19,
    lowStockThreshold: 12,
    status: "active",
    featured: false,
    fabric: "Wool Blend",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    variants: variants(["S", "M", "L", "XL"], ["Black"], 5),
    shortDescription: "Two-piece slim suit with a notch lapel and half canvas.",
    createdAt: "2026-03-29T09:00:00Z",
    updatedAt: "2026-06-24T09:00:00Z",
  },
]
