import type { ReviewDetail } from "@/types"

/**
 * Realistic review book for T-Mark Apparel — spans the full 1–5★ range,
 * every moderation state, photo reviews, admin replies and extracted
 * insights. Customers and products intentionally overlap with the Orders and
 * Customers data so the admin reads as one connected system.
 */
export const reviewDetails: ReviewDetail[] = [
  {
    id: "rev_01",
    reference: "REV-3041",
    rating: 5,
    title: "Exceptional stitching, flawless fit",
    body: "The craftsmanship is genuinely premium — the stitching is immaculate and the fabric drapes beautifully. Fit was perfect on the very first try. Worth every rupee.",
    photos: ["maroon", "ivory"],
    insights: [
      { label: "Perfect Fit", sentiment: "positive" },
      { label: "Excellent Stitching", sentiment: "positive" },
      { label: "Premium Fabric", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 34,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: true,
    featured: true,
    customer: {
      id: "cus_01",
      name: "Ahsan Raza",
      initials: "AR",
      vip: true,
      ordersCount: 7,
      lifetimeValue: 486000,
    },
    product: {
      id: "prod_01",
      name: "Ivory Embroidered Sherwani",
      image: "ivory",
      category: "Sherwanis",
      collection: "Wedding Collection",
      price: 42000,
      rating: 4.8,
      reviewsCount: 42,
    },
    reply: {
      id: "rp_01",
      author: "T-Mark Concierge",
      message:
        "Thank you, Ahsan — it was an honour to craft your wedding sherwani. Wishing you a lifetime of happiness.",
      at: "2026-07-04T09:00:00Z",
    },
    internalNote: "Feature on the product page — excellent photography.",
    activity: [
      { id: "ra1", type: "submitted", label: "Review submitted", at: "2026-07-03T12:00:00Z" },
      { id: "ra2", type: "approved", label: "Approved by Sana (Ops)", at: "2026-07-03T14:00:00Z" },
      { id: "ra3", type: "replied", label: "Reply published", at: "2026-07-04T09:00:00Z" },
      { id: "ra4", type: "featured", label: "Marked as featured", at: "2026-07-04T09:05:00Z" },
    ],
    createdAt: "2026-07-03T12:00:00Z",
    updatedAt: "2026-07-04T09:05:00Z",
  },
  {
    id: "rev_02",
    reference: "REV-3040",
    rating: 4,
    title: "Beautiful drape, delivery was slow",
    body: "The suit looks superb and the cut is elegant. Only gripe is that delivery took longer than the estimate — otherwise a wonderful piece.",
    photos: ["charcoal"],
    insights: [
      { label: "Elegant Cut", sentiment: "positive" },
      { label: "Late Delivery", sentiment: "negative" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 18,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_09",
      name: "Bilal Khan",
      initials: "BK",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 61000,
    },
    product: {
      id: "prod_02",
      name: "Charcoal Three-Piece Suit",
      image: "charcoal",
      category: "Western Suits",
      collection: "Best Sellers",
      price: 44000,
      rating: 4.4,
      reviewsCount: 28,
    },
    reply: {
      id: "rp_02",
      author: "T-Mark Concierge",
      message:
        "Thank you for the kind words, Bilal. We're reviewing our courier timelines and apologise for the wait.",
      at: "2026-07-03T10:00:00Z",
    },
    internalNote: null,
    activity: [
      { id: "ra5", type: "submitted", label: "Review submitted", at: "2026-07-02T16:30:00Z" },
      { id: "ra6", type: "approved", label: "Approved by Sana (Ops)", at: "2026-07-02T18:00:00Z" },
      { id: "ra7", type: "replied", label: "Reply published", at: "2026-07-03T10:00:00Z" },
    ],
    createdAt: "2026-07-02T16:30:00Z",
    updatedAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "rev_03",
    reference: "REV-3039",
    rating: 3,
    title: "Good quality but sizing ran small",
    body: "The waistcoat is well made and the fabric is nice, but it ran noticeably small across the chest. Had to get it altered locally.",
    photos: [],
    insights: [
      { label: "Runs Small", sentiment: "negative" },
      { label: "Good Quality", sentiment: "positive" },
    ],
    status: "pending",
    verifiedPurchase: true,
    helpfulCount: 7,
    reportedCount: 0,
    fitFeedback: "runs_small",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_03",
      name: "Hamza Sheikh",
      initials: "HS",
      vip: false,
      ordersCount: 1,
      lifetimeValue: 52000,
    },
    product: {
      id: "prod_03",
      name: "Navy Classic Waistcoat",
      image: "navy",
      category: "Waistcoats",
      collection: "New Arrivals",
      price: 12000,
      rating: 3.9,
      reviewsCount: 19,
    },
    reply: null,
    internalNote: "Third sizing complaint on this SKU — flag to product team.",
    activity: [
      { id: "ra8", type: "submitted", label: "Review submitted", at: "2026-07-02T09:10:00Z" },
    ],
    createdAt: "2026-07-02T09:10:00Z",
    updatedAt: "2026-07-02T09:10:00Z",
  },
  {
    id: "rev_04",
    reference: "REV-3038",
    rating: 5,
    title: "Embroidery exactly as pictured",
    body: "Beautiful tone-on-tone embroidery, precisely as shown online. The packaging felt genuinely luxurious. Highly recommend to anyone hesitating.",
    photos: ["ivory", "sand", "maroon"],
    insights: [
      { label: "Beautiful Embroidery", sentiment: "positive" },
      { label: "Luxury Packaging", sentiment: "positive" },
      { label: "As Pictured", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 41,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: true,
    customer: {
      id: "cus_06",
      name: "Usman Tariq",
      initials: "UT",
      vip: false,
      ordersCount: 9,
      lifetimeValue: 231400,
    },
    product: {
      id: "prod_04",
      name: "Ivory Embroidered Shalwar Kameez",
      image: "ivory",
      category: "Shalwar Kameez",
      collection: "Wedding Collection",
      price: 28000,
      rating: 4.7,
      reviewsCount: 36,
    },
    reply: null,
    internalNote: null,
    activity: [
      { id: "ra9", type: "submitted", label: "Review submitted", at: "2026-07-01T14:20:00Z" },
      { id: "ra10", type: "approved", label: "Approved by Sana (Ops)", at: "2026-07-01T16:00:00Z" },
      { id: "ra11", type: "featured", label: "Marked as featured", at: "2026-07-01T16:10:00Z" },
    ],
    createdAt: "2026-07-01T14:20:00Z",
    updatedAt: "2026-07-01T16:10:00Z",
  },
  {
    id: "rev_05",
    reference: "REV-3037",
    rating: 2,
    title: "Fabric thinner than expected",
    body: "For this price point I expected a heavier, more substantial fabric. It photographs well but feels thin in person. Disappointed.",
    photos: ["black"],
    insights: [
      { label: "Thin Fabric", sentiment: "negative" },
      { label: "Overpriced", sentiment: "negative" },
    ],
    status: "pending",
    verifiedPurchase: true,
    helpfulCount: 12,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_10",
      name: "Zeeshan Ali",
      initials: "ZA",
      vip: false,
      ordersCount: 1,
      lifetimeValue: 9800,
    },
    product: {
      id: "prod_05",
      name: "Black Slim Western Suit",
      image: "black",
      category: "Western Suits",
      collection: "New Arrivals",
      price: 38000,
      rating: 3.4,
      reviewsCount: 22,
    },
    reply: null,
    internalNote: "Needs a considered reply — offer QA review of the batch.",
    activity: [
      { id: "ra12", type: "submitted", label: "Review submitted", at: "2026-06-30T19:45:00Z" },
    ],
    createdAt: "2026-06-30T19:45:00Z",
    updatedAt: "2026-06-30T19:45:00Z",
  },
  {
    id: "rev_06",
    reference: "REV-3036",
    rating: 5,
    title: "Bespoke suit is a masterpiece",
    body: "My ninth order and still they exceed expectations. The bespoke navy suit fits like a glove — working cuffs, perfect break, impeccable finish.",
    photos: ["navy", "charcoal"],
    insights: [
      { label: "Perfect Fit", sentiment: "positive" },
      { label: "Excellent Stitching", sentiment: "positive" },
      { label: "Great Service", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 27,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_02",
      name: "Imran Yousaf",
      initials: "IY",
      vip: true,
      ordersCount: 9,
      lifetimeValue: 612000,
    },
    product: {
      id: "prod_06",
      name: "Navy Three-Piece Bespoke Suit",
      image: "navy",
      category: "Western Suits",
      collection: "Best Sellers",
      price: 46500,
      rating: 4.9,
      reviewsCount: 31,
    },
    reply: {
      id: "rp_03",
      author: "T-Mark Concierge",
      message: "Always a pleasure, Imran. Thank you for your continued trust.",
      at: "2026-06-29T12:00:00Z",
    },
    internalNote: null,
    activity: [
      { id: "ra13", type: "submitted", label: "Review submitted", at: "2026-06-28T11:00:00Z" },
      { id: "ra14", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-28T13:00:00Z" },
      { id: "ra15", type: "replied", label: "Reply published", at: "2026-06-29T12:00:00Z" },
    ],
    createdAt: "2026-06-28T11:00:00Z",
    updatedAt: "2026-06-29T12:00:00Z",
  },
  {
    id: "rev_07",
    reference: "REV-3035",
    rating: 1,
    title: "Not what I ordered",
    body: "This is spam-like promotional content with links. Should not be here.",
    photos: [],
    insights: [{ label: "Spam", sentiment: "negative" }],
    status: "flagged",
    verifiedPurchase: false,
    helpfulCount: 0,
    reportedCount: 4,
    fitFeedback: null,
    pinned: false,
    featured: false,
    customer: {
      id: "cus_unknown",
      name: "Guest User",
      initials: "GU",
      vip: false,
      ordersCount: 0,
      lifetimeValue: 0,
    },
    product: {
      id: "prod_05",
      name: "Black Slim Western Suit",
      image: "black",
      category: "Western Suits",
      collection: "New Arrivals",
      price: 38000,
      rating: 3.4,
      reviewsCount: 22,
    },
    reply: null,
    internalNote: "Reported 4×. Unverified purchase — recommend rejecting.",
    activity: [
      { id: "ra16", type: "submitted", label: "Review submitted", at: "2026-06-27T22:00:00Z" },
      { id: "ra17", type: "reported", label: "Reported by 4 customers", at: "2026-06-28T08:00:00Z" },
    ],
    createdAt: "2026-06-27T22:00:00Z",
    updatedAt: "2026-06-28T08:00:00Z",
  },
  {
    id: "rev_08",
    reference: "REV-3034",
    rating: 4,
    title: "Lovely kurta, runs a touch large",
    body: "Gorgeous emerald colour and soft silk. It runs a little large so consider sizing down. Still very happy with it.",
    photos: ["emerald"],
    insights: [
      { label: "Runs Large", sentiment: "negative" },
      { label: "Premium Fabric", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 15,
    reportedCount: 0,
    fitFeedback: "runs_large",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_05",
      name: "Fahad Malik",
      initials: "FM",
      vip: false,
      ordersCount: 4,
      lifetimeValue: 98000,
    },
    product: {
      id: "prod_07",
      name: "Emerald Silk Kurta",
      image: "emerald",
      category: "Kurtas",
      collection: "Summer Collection",
      price: 10400,
      rating: 4.3,
      reviewsCount: 24,
    },
    reply: null,
    internalNote: null,
    activity: [
      { id: "ra18", type: "submitted", label: "Review submitted", at: "2026-06-26T10:00:00Z" },
      { id: "ra19", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-26T12:00:00Z" },
    ],
    createdAt: "2026-06-26T10:00:00Z",
    updatedAt: "2026-06-26T12:00:00Z",
  },
  {
    id: "rev_09",
    reference: "REV-3033",
    rating: 5,
    title: "Worldwide shipping done right",
    body: "Shipped to Dubai in four days, beautifully packaged. The linen shalwar kameez is perfect for the heat. Superb service end to end.",
    photos: ["sand"],
    insights: [
      { label: "Fast Delivery", sentiment: "positive" },
      { label: "Luxury Packaging", sentiment: "positive" },
      { label: "Great Service", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 22,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_04",
      name: "Omar Farooq",
      initials: "OF",
      vip: true,
      ordersCount: 5,
      lifetimeValue: 214000,
    },
    product: {
      id: "prod_08",
      name: "Sand Linen Shalwar Kameez",
      image: "sand",
      category: "Shalwar Kameez",
      collection: "Summer Collection",
      price: 15600,
      rating: 4.6,
      reviewsCount: 18,
    },
    reply: null,
    internalNote: null,
    activity: [
      { id: "ra20", type: "submitted", label: "Review submitted", at: "2026-06-25T09:00:00Z" },
      { id: "ra21", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-25T11:00:00Z" },
    ],
    createdAt: "2026-06-25T09:00:00Z",
    updatedAt: "2026-06-25T11:00:00Z",
  },
  {
    id: "rev_10",
    reference: "REV-3032",
    rating: 2,
    title: "Colour was off",
    body: "The maroon looked much brighter online. In person it's quite dark. The stitching is fine but the colour mismatch was disappointing.",
    photos: ["maroon"],
    insights: [
      { label: "Colour Mismatch", sentiment: "negative" },
      { label: "Good Stitching", sentiment: "positive" },
    ],
    status: "hidden",
    verifiedPurchase: true,
    helpfulCount: 9,
    reportedCount: 1,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_12",
      name: "Noman Siddiqui",
      initials: "NS",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 21000,
    },
    product: {
      id: "prod_09",
      name: "Maroon Velvet Waistcoat",
      image: "maroon",
      category: "Waistcoats",
      collection: "Festive",
      price: 14000,
      rating: 3.8,
      reviewsCount: 16,
    },
    reply: {
      id: "rp_04",
      author: "T-Mark Concierge",
      message:
        "We're sorry the shade didn't match, Noman. We've updated the product photography and would love to make this right.",
      at: "2026-06-25T10:00:00Z",
    },
    internalNote: "Hidden pending re-shoot of product images.",
    activity: [
      { id: "ra22", type: "submitted", label: "Review submitted", at: "2026-06-24T18:00:00Z" },
      { id: "ra23", type: "replied", label: "Reply published", at: "2026-06-25T10:00:00Z" },
    ],
    createdAt: "2026-06-24T18:00:00Z",
    updatedAt: "2026-06-25T10:00:00Z",
  },
  {
    id: "rev_11",
    reference: "REV-3031",
    rating: 5,
    title: "Wedding sherwani beyond expectations",
    body: "Ordered from Riyadh for my wedding. The high collar and gold thread detailing are exquisite. Master Rehman is a true artist.",
    photos: ["ivory", "maroon"],
    insights: [
      { label: "Beautiful Embroidery", sentiment: "positive" },
      { label: "Perfect Fit", sentiment: "positive" },
      { label: "Great Service", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 38,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: true,
    featured: true,
    customer: {
      id: "cus_05b",
      name: "Abdullah Al-Rashid",
      initials: "AA",
      vip: true,
      ordersCount: 6,
      lifetimeValue: 331000,
    },
    product: {
      id: "prod_01",
      name: "Ivory Embroidered Sherwani",
      image: "ivory",
      category: "Sherwanis",
      collection: "Wedding Collection",
      price: 42000,
      rating: 4.8,
      reviewsCount: 42,
    },
    reply: {
      id: "rp_05",
      author: "T-Mark Concierge",
      message: "Congratulations, Abdullah! It was a privilege to be part of your day.",
      at: "2026-06-24T09:00:00Z",
    },
    internalNote: null,
    activity: [
      { id: "ra24", type: "submitted", label: "Review submitted", at: "2026-06-23T15:00:00Z" },
      { id: "ra25", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-23T17:00:00Z" },
      { id: "ra26", type: "replied", label: "Reply published", at: "2026-06-24T09:00:00Z" },
    ],
    createdAt: "2026-06-23T15:00:00Z",
    updatedAt: "2026-06-24T09:00:00Z",
  },
  {
    id: "rev_12",
    reference: "REV-3030",
    rating: 4,
    title: "Great coat, minor loose thread",
    body: "The prince coat is stunning and the velvet is rich. Found one loose thread on the cuff but easily fixed. Would order again.",
    photos: [],
    insights: [
      { label: "Premium Fabric", sentiment: "positive" },
      { label: "Minor Defect", sentiment: "negative" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 11,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_08",
      name: "Kamran Shah",
      initials: "KS",
      vip: false,
      ordersCount: 3,
      lifetimeValue: 176000,
    },
    product: {
      id: "prod_10",
      name: "Black Velvet Prince Coat",
      image: "black",
      category: "Prince Coats",
      collection: "Festive",
      price: 58000,
      rating: 4.5,
      reviewsCount: 14,
    },
    reply: null,
    internalNote: null,
    activity: [
      { id: "ra27", type: "submitted", label: "Review submitted", at: "2026-06-22T13:00:00Z" },
      { id: "ra28", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-22T15:00:00Z" },
    ],
    createdAt: "2026-06-22T13:00:00Z",
    updatedAt: "2026-06-22T15:00:00Z",
  },
  {
    id: "rev_13",
    reference: "REV-3029",
    rating: 3,
    title: "Nice but delivery delayed twice",
    body: "The kameez itself is good quality. However the delivery was rescheduled twice and customer support was slow to respond.",
    photos: [],
    insights: [
      { label: "Late Delivery", sentiment: "negative" },
      { label: "Slow Support", sentiment: "negative" },
    ],
    status: "pending",
    verifiedPurchase: true,
    helpfulCount: 5,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_11",
      name: "Ali Raza Bukhari",
      initials: "AB",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 92000,
    },
    product: {
      id: "prod_04",
      name: "Ivory Embroidered Shalwar Kameez",
      image: "ivory",
      category: "Shalwar Kameez",
      collection: "Wedding Collection",
      price: 28000,
      rating: 4.7,
      reviewsCount: 36,
    },
    reply: null,
    internalNote: "Support SLA breach — loop in logistics.",
    activity: [
      { id: "ra29", type: "submitted", label: "Review submitted", at: "2026-06-21T11:00:00Z" },
    ],
    createdAt: "2026-06-21T11:00:00Z",
    updatedAt: "2026-06-21T11:00:00Z",
  },
  {
    id: "rev_14",
    reference: "REV-3028",
    rating: 5,
    title: "Best waistcoat I own",
    body: "Impeccable tailoring and the charcoal wool is beautifully weighted. Fits true to size. This is my go-to for formal events now.",
    photos: ["charcoal"],
    insights: [
      { label: "Perfect Fit", sentiment: "positive" },
      { label: "Premium Fabric", sentiment: "positive" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 19,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_09b",
      name: "Saad Iqbal",
      initials: "SI",
      vip: false,
      ordersCount: 3,
      lifetimeValue: 74000,
    },
    product: {
      id: "prod_11",
      name: "Charcoal Wool Waistcoat",
      image: "charcoal",
      category: "Waistcoats",
      collection: "Best Sellers",
      price: 8900,
      rating: 4.6,
      reviewsCount: 27,
    },
    reply: null,
    internalNote: null,
    activity: [
      { id: "ra30", type: "submitted", label: "Review submitted", at: "2026-06-20T16:00:00Z" },
      { id: "ra31", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-20T18:00:00Z" },
    ],
    createdAt: "2026-06-20T16:00:00Z",
    updatedAt: "2026-06-20T18:00:00Z",
  },
  {
    id: "rev_15",
    reference: "REV-3027",
    rating: 1,
    title: "Arrived damaged",
    body: "The package was crushed and the garment had a visible tear. Very disappointing for the price. Awaiting a replacement.",
    photos: ["black"],
    insights: [
      { label: "Damaged on Arrival", sentiment: "negative" },
      { label: "Poor Packaging", sentiment: "negative" },
    ],
    status: "pending",
    verifiedPurchase: true,
    helpfulCount: 3,
    reportedCount: 0,
    fitFeedback: null,
    pinned: false,
    featured: false,
    customer: {
      id: "cus_12b",
      name: "Junaid Akbar",
      initials: "JA",
      vip: false,
      ordersCount: 2,
      lifetimeValue: 64000,
    },
    product: {
      id: "prod_12",
      name: "Navy Made-to-Measure Waistcoat",
      image: "navy",
      category: "Waistcoats",
      collection: "New Arrivals",
      price: 24000,
      rating: 4.1,
      reviewsCount: 12,
    },
    reply: null,
    internalNote: "Urgent — arrange replacement & courier claim.",
    activity: [
      { id: "ra32", type: "submitted", label: "Review submitted", at: "2026-06-19T20:00:00Z" },
    ],
    createdAt: "2026-06-19T20:00:00Z",
    updatedAt: "2026-06-19T20:00:00Z",
  },
  {
    id: "rev_16",
    reference: "REV-3026",
    rating: 4,
    title: "Elegant and comfortable",
    body: "The summer kurta is light and breathable, perfect for Doha. Colour is rich and true to the photos. Would have liked more size options.",
    photos: [],
    insights: [
      { label: "Comfortable", sentiment: "positive" },
      { label: "Limited Sizes", sentiment: "negative" },
    ],
    status: "approved",
    verifiedPurchase: true,
    helpfulCount: 8,
    reportedCount: 0,
    fitFeedback: "true_to_size",
    pinned: false,
    featured: false,
    customer: {
      id: "cus_03b",
      name: "Yousaf Nawaz",
      initials: "YN",
      vip: true,
      ordersCount: 8,
      lifetimeValue: 540000,
    },
    product: {
      id: "prod_07",
      name: "Emerald Silk Kurta",
      image: "emerald",
      category: "Kurtas",
      collection: "Summer Collection",
      price: 10400,
      rating: 4.3,
      reviewsCount: 24,
    },
    reply: null,
    internalNote: null,
    activity: [
      { id: "ra33", type: "submitted", label: "Review submitted", at: "2026-06-18T12:00:00Z" },
      { id: "ra34", type: "approved", label: "Approved by Sana (Ops)", at: "2026-06-18T14:00:00Z" },
    ],
    createdAt: "2026-06-18T12:00:00Z",
    updatedAt: "2026-06-18T14:00:00Z",
  },
]
